### ISSUE TITLE
 Error: spawn \angular-seed\node_modules\.npminstall\protractor\3.3.0\.bin\webdriver-manager.cmd ENOENT

### ISSUE THREAD

**Issue by kanlidy** [mgechev/angular-seed#1444]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

**Steps to reproduce and a minimal demo of the problem**
1. try remove node_modules, retry npm install
2. try remove all the project files, retry git clone and npm install 
Problem still 

_What steps should we try in your demo to see the problem?_
1. after `git clone`
2. npm install

**Current behavior**

    [17:34:17] Starting 'webdriver'...
    Error: spawn E:\projects\LearnAngular\ng-demo\angular-seed\node_modules\.npminstall\protractor\3.3.0\.bin\webdriver-manager.cmd ENOENT
        at exports._errnoException (util.js:1012:11)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
        at onErrorNT (internal/child_process.js:348:16)
        at _combinedTickCallback (internal/process/next_tick.js:74:11)
        at process._tickCallback (internal/process/next_tick.js:98:9)
        at Module.runMain (module.js:577:11)
        at run (bootstrap_node.js:352:7)
        at startup (bootstrap_node.js:144:9)
        at bootstrap_node.js:467:3
    Error: post install error, please remove node_modules before retry!
    Run "C:\WINDOWS\system32\cmd.exe /d /s /c gulp check.versions && gulp build.bundle.rxjs && npm prune && gulp webdriver && gulp print.banner" error, exit code 1
    Error: post install error, please remove node_modules before retry!
    Run "C:\WINDOWS\system32\cmd.exe /d /s /c gulp check.versions && gulp build.bundle.rxjs && npm prune && gulp webdriver && gulp print.banner" error, exit code 1
        at ChildProcess.proc.on.code (C:\Users\work-liwei\AppData\Roaming\npm\node_modules\cnpm\node_modules\runscript\index.js:67:21)
        at emitTwo (events.js:106:13)
        at ChildProcess.emit (events.js:191:7)
        at maybeClose (internal/child_process.js:852:16)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)

**Expected/desired behavior**

**Other information**

`npm's version: 3.10.3`
`node version: v6.3.1`
`the latest angular-seed`

**Comment by kanlidy** [comment]
![20161010100109](https://cloud.githubusercontent.com/assets/5557262/19225518/b3191964-8ed0-11e6-9901-1735ac9f9f4e.jpg)

Use `npm run start` can load the project and run...

**Comment by mgechev** [comment]
Yes, you need to run `npm start` once the installation is completed.

The `Duplicate identifier` should have been caused by a modification of the seed since it is not reproducible in the Windows CI, neither or my parallels Windows VM.
