### ISSUE TITLE
"Unexpected token /" in tslint.json error during npm install 

### ISSUE THREAD

**Issue by hhubik** [mgechev/angular-seed#1445]
**Steps to reproduce and a minimal demo of the problem**
Pulled the latest Seed code last night. 
Get the following error when running `npm install`:
```
angular2-seed@0.0.0 postinstall D:\Users\hubert\Documents\Angular2Dev\angular2-seed
 gulp check.versions && gulp build.bundle.rxjs && npm prune && gulp webdriver && gulp print.banner

module.js:433
    throw err;
    ^

SyntaxError: .../tslint.json: Unexpected token /
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:430:27)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at customRules (...tools\config\seed.config.js:254:20)
    at ProjectConfig.SeedConfig (...tools\config\seed.config.js:61:32)
    at new ProjectConfig (...tools\config\project.config.js:12:16)
    at Object.<anonymous> (...tools\config.js:3:14)
```

The error goes away when I remove the following comment from my `tslint.json` file in the root directory of my project:
`//overwrite rules defined in seed.tslint.json here or add additional rules`

Running tslint ver 3.14.0 on Windows 8.1.

**Comment by mgechev** [comment]
@hhubik should be fine now.
