### ISSUE TITLE
npm install fails (cannot find module print.banner)

### ISSUE THREAD

**Issue by hhubik** [mgechev/angular-seed#1451]
**Steps to reproduce and a minimal demo of the problem**
Pulled the latest Seed code yesterday and started having trouble with npm install that now fails with the following message:
`Error: Cannot find module '...tools\tasks\seed\print.banner'
`

```
...
selenium standalone is up to date.
chromedriver is up to date.
[23:22:21] Finished 'webdriver' after 3.46 s
[23:22:23] Loading tasks folder ...tools\tasks\seed
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\seed\build.assets.dev
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\seed\build.assets.prod
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\seed\build.bundle.rxjs
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\seed\build.bundles.app.exp
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\seed\build.bundles.app
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\seed\build.bundles
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\seed\build.docs
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\seed\build.html_css
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\seed\build.index.dev
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\seed\build.index.prod
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\seed\build.js.dev
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\seed\build.js.e2e
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\seed\build.js.prod.exp
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\seed\build.js.prod
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\seed\build.js.test
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\seed\build.js.tools
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\seed\check.versions
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\seed\clean.all
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\seed\clean.coverage
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\seed\clean.dev
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\seed\clean.prod
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\seed\clean.tools
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\seed\compile.ahead.prod
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\seed\copy.prod
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\seed\css-lint
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\seed\e2e
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\seed\generate.manifest
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\seed\karma.run
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\seed\karma.run.with_coverage
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\seed\karma.watch
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\seed\minify.bundles
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\seed\print.banner
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\seed\serve.coverage
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\seed\serve.coverage.watch
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\seed\serve.docs
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\seed\server.prod
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\seed\server.start
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\seed\start.deving
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\seed\tslint
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\seed\watch.dev
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\seed\watch.e2e
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\seed\watch.test
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\seed\webdriver
[23:22:23] Loading tasks folder ...tools\tasks\project
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\project\build.fonts
[23:22:23] Registering task ~\Documents\Angular2Dev\angular2-seed\tools\tasks\project\sample.task
[23:22:23] Using gulpfile ~\Documents\Angular2Dev\angular2-seed\gulpfile.js
[23:22:23] Starting 'print.banner'...
[23:22:23] 'print.banner' errored after 524 μs
[23:22:23] Error: Cannot find module '...tools\tasks\seed\print.banner'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Gulp.<anonymous> (...tools\utils\seed\tasks_tools.js:17:20)
    at module.exports (...node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (...node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (...node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (...node_modules\orchestrator\index.js:134:8)
    at ...node_modules\gulp\bin\gulp.js:129:20

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN optional Skipping failed optional dependency /gulp-watch/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.10.0
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed@0.0.0 postinstall: `gulp check.versions && gulp build.bundle.rxjs && npm prune && gulp webdriver && gulp print.banner`
npm ERR! Exit status 1


```

**Comment by mgechev** [comment]
Most likely you're missing the most recent changes of the seed.

Take [this task](https://github.com/mgechev/angular-seed/blob/master/tools/tasks/seed/print.banner.ts) and place it in `tools/seed/print.banner.ts`.

**Comment by hhubik** [comment]
I already have the `print.banner.ts` file in my project and its content is exactly the same as the content of the corresponding Seed file on github (pointed to by "this task" in your message).  I got that when I did ` git pull upstream master` yesterday.  And npm install started failing **after** I did the pull.

**Comment by mgechev** [comment]
I'll try to reproduce it on Windows tomorrow.

**Comment by hhubik** [comment]
I am new to this front-end stuff, and especially the Seed project build process is a still a bit of a mystery for me.  But let me know if I can help.

Two observations:

1. Every `.ts` file in my `\tools\tasks\seed` has a corresponding `.js` and `.js.map` file ... except for `print.banner.ts`.
2. When I run `npm start` after the failed `npm install`, my app seems to run normally.

**Comment by hhubik** [comment]
Just did another pull from the Seed repo.  npm install still fails with the same message.

**Comment by mgechev** [comment]
> Every .ts file in my \tools\tasks\seed has a corresponding .js and .js.map file ... except for print.banner.ts.

Oh @hhubik thanks for this information. It seems you're using Windows, so I'd recommend you to go to the root of your project and run: `tsc`. This will compile all the files in `tools` to JavaScript and also solve your problem.


The problem comes from here: we're using TypeScript for our build (statically typed so we have less bugs and better tooling). Gulp allows us to define all our gulp tasks in TypeScript and if it doesn't find any `gulpfile.ts` it automatically invokes `gulpfile.js` and requires all the JavaScript alternatives of your `tools/**/*.ts` files, ignoring the TypeScript files themselves.

Somehow, you've compiled the files in `tools` to JavaScript. When you have pulled the latest changes of Angular Seed you've gotten the `print.banner` task but since all other files has their JavaScript version, gulp is ignoring `print.banner` because it has only a TypeScript one.

Good luck! I hope this helped.

**Comment by hhubik** [comment]
Thanks for the suggestion. Yes, I am using Windows and I might have run tsc at some point.  Would a better solution be to just delete all `js` and `js.map` files from `tools` so that the "on-the-fly" compilation of the `ts` files would work as intended?  This would avoid the same problem the next time a new task is added. Am I right?

**Comment by mgechev** [comment]
Both will work but in Windows compiling the entire `tools` directory to JavaScript will bring a performance boost. Take a look [here](https://github.com/mgechev/angular-seed/wiki/Speed-up-the-build-on-Windows).

**Comment by hhubik** [comment]
@mgechev - thanks for your help.  That fixed the problem.

**Comment by samudra77** [comment]
Hi, when I run the install , I am getting  this error on windows
[14:41:33] 'print.banner' errored after 130 ms
[14:41:33] Error: Cannot find module 'supports-color'

**Comment by samudra77** [comment]
Added this to package.json and it fixed the error "supports-color": "^3.1.2".

However I have errors in webdriver

[14:51:30] I/downloader - selenium standalone: downloading version 2.53.1
[14:51:30] I/downloader - curl -o C:\work\angular2-cft-seed\node_modules\protractor\node_modules\webdriver-manager\se
lenium/selenium-server-standalone-2.53.1.jar https://selenium-release.storage.googleapis.com/2.53/selenium-server-sta
ndalone-2.53.1.jar
[14:51:30] I/downloader - chromedriver: downloading version 2.24
[14:51:30] I/downloader - curl -o C:\work\angular2-cft-seed\node_modules\protractor\node_modules\webdriver-manager\se
lenium/chromedriver_2.24win32.zip https://chromedriver.storage.googleapis.com/2.24/chromedriver_win32.zip
[14:51:30] I/downloader - geckodriver: downloading version v0.9.0
[14:51:30] I/downloader - curl -o C:\work\angular2-cft-seed\node_modules\protractor\node_modules\webdriver-manager\se
lenium/geckodriver-v0.9.0-win64.zip https://github.com/mozilla/geckodriver/releases/download/v0.9.0/geckodriver-v0.9.
0-win64.zip
[14:51:30] E/downloader - { [Error: getaddrinfo ENOTFOUND selenium-release.storage.googleapis.com selenium-release.st

I am behind a corporate proxy. Node is working with proxy config set. But is there something else I need to do to for this error ?

**Comment by mgechev** [comment]
Here's an [answer is SO that I found](https://stackoverflow.com/questions/29483126/cant-update-chromedriver-and-seleniumrelease).

**Comment by samudra77** [comment]
Thanks , will try this.
