### ISSUE TITLE
lodash doesn't compile to production

### ISSUE THREAD

**Issue by grauschnabel** [mgechev/angular-seed#1463]
Hi there,

I try to build the prodution using lodash, but I get the following error:

    npm run build.prod

produces this output

```
[11:01:08] Starting 'build.js.prod'...

/home/martin/Projects/lf/client/node_modules/lodash/lodash.js:479
      case 0: return func.call(thisArg);
                          ^
SyntaxError: Invalid or unexpected token
    at /home/martin/Projects/lf/client/node_modules/lodash/lodash.js:14740:16
    at apply (/home/martin/Projects/lf/client/node_modules/lodash/lodash.js:479:27)
    at /home/martin/Projects/lf/client/node_modules/lodash/lodash.js:15124:16
    at apply (/home/martin/Projects/lf/client/node_modules/lodash/lodash.js:481:27)
    at /home/martin/Projects/lf/client/node_modules/lodash/lodash.js:6499:16
    at template (/home/martin/Projects/lf/client/node_modules/lodash/lodash.js:14739:20)
    at DestroyableTransform._transform (/home/martin/Projects/lf/client/node_modules/gulp-template/index.js:20:14)
    at DestroyableTransform.Transform._read (/home/martin/Projects/lf/client/node_modules/gulp-template/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Readable.read (/home/martin/Projects/lf/client/node_modules/gulp-template/node_modules/readable-stream/lib/_stream_readable.js:357:10)
    at flow (/home/martin/Projects/lf/client/node_modules/gulp-template/node_modules/readable-stream/lib/_stream_readable.js:727:26)

npm ERR! Linux 4.7.6-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build.prod"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! lf-client@0.0.1 build.prod: `gulp build.prod --color --config-env prod`
npm ERR! Exit status 1
```

I tried to figure it out by myself, but I don't know how to solve this, and I'm not sure if it is a bug in angular2-seed, but lodash is written to be supported...

**Comment by ruffiem** [comment]
Here how to set up lodash properly : 

Run : 

```bash
$ npm i lodash@latest @types/lodash@latest --save-dev
```

Open the file `project.config.ts`located at `tools/config` and the following lines
```ts
this.SYSTEM_CONFIG_DEV.paths['lodash'] = `${this.APP_BASE}node_modules/lodash/`;
this.SYSTEM_BUILDER_CONFIG.packages['lodash'] = { main: 'lodash.js', defaultExtension: 'js' };
```

Then import it to your component:

```ts
import * as _ from 'lodash';
// or
import { filter } from 'lodash';
```

**Comment by mgechev** [comment]
@ruffiem thanks for the comment!

**Comment by grauschnabel** [comment]
This does not solve my problem, same error as above.

I don't use lodash by myself, but thought angular2-seed would use it.  Removing lodash by npm uninstall lodash (its not in the package.json here) also leads to an error:

```
[11:38:45] 'css-lint' errored after 296 ms
[11:38:45] Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/martin/Projects/lf/client/node_modules/postcss-reporter/lib/reporter.js:2:9)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
[11:38:45] 'build.prod' errored after 8.89 s
[11:38:45] Error in plugin 'run-sequence(css-lint)'
Message:
    Cannot find module 'lodash'
Details:
    code: MODULE_NOT_FOUND
Stack:
Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/martin/Projects/lf/client/node_modules/postcss-reporter/lib/reporter.js:2:9)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

and the postcss-reporter is in my package.json because its angular2-seed  default.
Any further hints?

**Comment by dcarabott** [comment]
I'm getting this error when running: 

`gulp  transpile.bundles.rollup.aot`

The error occurs when starting `transpile.bundles.rollup.aot`

`case 0: return func.call(thisArg);`

I have tried @ruffiem's solution but I still got the same error. 

Any Insights?

**Comment by lakshmikant4u** [comment]
@mgechev tried solution provided by @ruffiem but still its not working.
Currently using angular-seed 2.1.2, Any suggestions on packages upgradation would be of great help.
Thanks in advance.
