### ISSUE TITLE
Default project with no modification: cannot run build.prod.exp

### ISSUE THREAD

**Issue by RoxKilly** [mgechev/angular-seed#1469]
**Steps to reproduce and a minimal demo of the problem**

I'm following the ["*How to start*" guide](https://github.com/mgechev/angular-seed#how-to-start). I have:

1. cloned the repo
2. `npm install`: a few errors about Peer dependency, but seemed to complete the install
3. `npm start`: OK; app runs in browser
4. `npm run serve.prod`: OK; build completes and app runs in the browser
5. `npm run build.prod.exp`: Fails. errors below

**Current behavior**
```
Starting 'compile.ahead.prod'...
 
Error: undefined, resolving symbol ApplicationModule in C:/websites/github/roxkilly/angular-seed/node_modules/@angular/core/src/application_module.d.ts
    at simplifyInContext (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/static_reflector.ts:528:15)
    at StaticReflector.simplify (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/static_reflector.ts:532:18)
    at StaticReflector.annotations (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/static_reflector.ts:92:28)
    at _loop_1 (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/codegen.ts:63:48)
    at CodeGenerator.readFileMetadata (/websites/github/roxkilly/angular-seed/node_modules/@angular/compiler-cli/src/codegen.js:66:13)
    at /Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/codegen.ts:105:56
    at Array.map (native)
    at CodeGenerator.codegen (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/codegen.ts:105:33)
    at codegen (/websites/github/roxkilly/angular-seed/tools/tasks/seed/compile.ahead.prod.ts:14:69)
    at Object.main (/websites/github/roxkilly/tools/@angular/tsc-wrapped/src/main.ts:44:12)
Compilation failed
```

**Expected/desired behavior**

Since the only change I made was to add some entries to `.gitignore`, I expected ahead-of-time builds to work out of the box.

**Other information**
`Windows 7 x64`, `node 4.5.0`, `npm 2.15.9`. Local typescript is `tsc 2.0.3`

Master branch was cloned on `2016-10-11`

**Comment by RoxKilly** [comment]
To fix:
1. I installed the latest Node. Now, `node 6.8.0`, `npm 3.10.8`
2. I re-ran `npm install`
3. I re-ran `npm run build.prod.exp`, and it completed without error.

The [docs claim](https://github.com/mgechev/angular-seed#how-to-start):
> this seed project requires node v4.x.x or higher and npm 2.14.7

Since my original setup met these requirements, I thought the problem was elsewhere.  On `Windows 7` at least, the minimum requirements to install, then run the AoT build are higher than the docs suggest.

Feel free to close.

**Comment by mgechev** [comment]
Thanks. Would you update the readme with these specific requirements for AoT?
