### ISSUE TITLE
The build system is broken after a new npm install

### ISSUE THREAD

**Issue by jimmybillings** [mgechev/angular-seed#1476]
Running the app after a fresh npm install now fails, assume dependency conflict somewhere.

**Steps to reproduce and a minimal demo of the problem**
clone the repo, npm install, npm start

**Current behavior**
Build fails with the following error: 

'build.js.dev' errored after 188 ms
[15:24:25] Error: Cannot find module './src/init'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jbillings/sandbox/angular-seed/node_modules/gulp-typescript/node_modules/gulp-sourcemaps/index.js:4:9)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
[15:24:25] 'serve.dev' errored after 4.16 s
[15:24:25] Error in plugin 'run-sequence(build.js.dev)'

**Expected/desired behavior**
App runs

**Other information**
It mentions the gulp-sourcemap module as one of the sources for the error. I noticed that gulp-sourcemaps in included in the package.json file as: "gulp-sourcemaps": "2.0.0-alpha" however when I do a npm list it's at version 1.7.3 which seems strange, not sure if that could be causing it.

**Comment by njs50** [comment]
gulp-sourcemaps is currently broken. 

gulp-typescript has a dependency on it without a specific version which is causing the broken one to be loaded :-/

**Comment by njs50** [comment]
bleh, or maybe it's worse, gulp-typescript has a dep of vinyl-fs which has a dep of gulp-sourcemaps 1.6.0 which is the broken version, and is where that error is coming from.

**Comment by karlhiramoto** [comment]
More info:
https://github.com/floridoo/gulp-sourcemaps/issues/238

**Comment by mgechev** [comment]
I see https://github.com/floridoo/gulp-sourcemaps/issues/238 is closed. Is everything working fine now?

**Comment by 1thrasher** [comment]
Yes, removing `node_modules/gulp-typescript`, then `npm install` fixes the problem.
