### ISSUE TITLE
Live reload does not work.

### ISSUE THREAD

**Issue by jarrettj** [mgechev/angular-seed#1500]
Hi,

Cloned project.
npm install
npm start
Edited the index.html file in src/client
Edited about.component.html in src/client/app/about

App is not reloaded.

Output from npm start
```

[15:27:26] Requiring external module ts-node/register
[15:27:35] Loading tasks folder /var/www/wxyz/angular-seed/tools/tasks/seed
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/build.assets.dev
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/build.assets.prod
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/build.bundle.rxjs
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/build.bundles.app.exp
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/build.bundles.app
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/build.bundles
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/build.docs
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/build.html_css
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/build.index.dev
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/build.index.prod
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/build.js.dev
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/build.js.e2e
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/build.js.prod.exp
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/build.js.prod
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/build.js.test
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/build.tools
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/check.tools
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/check.versions
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/clean.all
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/clean.coverage
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/clean.dev
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/clean.prod
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/clean.tools
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/clear.files
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/compile.ahead.prod
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/copy.prod
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/e2e
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/generate.manifest
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/karma.run
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/karma.run.with_coverage
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/karma.watch
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/minify.bundles
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/print.banner
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/serve.coverage
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/serve.coverage.watch
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/serve.docs
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/server.prod
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/server.start
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/start.deving
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/tslint
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/watch.dev
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/watch.e2e
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/watch.test
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/seed/webdriver
[15:27:35] Loading tasks folder /var/www/wxyz/angular-seed/tools/tasks/project
[15:27:35] Registering task /var/www/wxyz/angular-seed/tools/tasks/project/sample.task
[15:27:35] Using gulpfile /var/www/wxyz/angular-seed/gulpfile.ts
[15:27:35] Starting 'serve.dev'...
[15:27:35] Starting 'build.dev'...
[15:27:35] Starting 'build.assets.dev'...
[15:27:36] Finished 'build.assets.dev' after 786 ms
[15:27:36] Starting 'build.html_css'...
[15:27:38] Finished 'build.html_css' after 2.58 s
[15:27:38] Starting 'build.js.dev'...
/var/www/wxyz/angular-seed/node_modules/@types/protractor/index.d.ts(28,45): error TS2339: Property 'Error' does not exist on type 'typeof error'.
/var/www/wxyz/angular-seed/node_modules/@types/protractor/index.d.ts(29,40): error TS2305: Module 'webdriver.error' has no exported member 'IErrorCode'.
/var/www/wxyz/angular-seed/node_modules/@types/protractor/index.d.ts(37,38): error TS2305: Module 'webdriver.logging' has no exported member 'ILevelValues'.
/var/www/wxyz/angular-seed/node_modules/@types/protractor/index.d.ts(39,67): error TS2305: Module 'webdriver.logging' has no exported member 'ILevel'.
/var/www/wxyz/angular-seed/node_modules/@types/protractor/index.d.ts(40,67): error TS2305: Module 'webdriver.logging' has no exported member 'ILevel'.
/var/www/wxyz/angular-seed/node_modules/@types/protractor/index.d.ts(287,39): error TS2339: Property 'stacktrace' does not exist on type 'typeof webdriver'.
/var/www/wxyz/angular-seed/node_modules/@types/protractor/index.d.ts(288,42): error TS2339: Property 'stacktrace' does not exist on type 'typeof webdriver'.
/var/www/wxyz/angular-seed/node_modules/@types/protractor/index.d.ts(303,35): error TS2305: Module 'webdriver' has no exported member 'stacktrace'.
/var/www/wxyz/angular-seed/node_modules/@types/protractor/index.d.ts(340,55): error TS2305: Module 'webdriver' has no exported member 'Locator'.
/var/www/wxyz/angular-seed/node_modules/@types/protractor/index.d.ts(414,52): error TS2305: Module 'webdriver' has no exported member 'Locator'.
/var/www/wxyz/angular-seed/node_modules/@types/protractor/index.d.ts(462,53): error TS2305: Module 'webdriver' has no exported member 'Locator'.
/var/www/wxyz/angular-seed/node_modules/@types/protractor/index.d.ts(664,29): error TS2305: Module 'webdriver' has no exported member 'Locator'.
/var/www/wxyz/angular-seed/node_modules/@types/protractor/index.d.ts(673,32): error TS2305: Module 'webdriver' has no exported member 'Locator'.
/var/www/wxyz/angular-seed/node_modules/@types/protractor/index.d.ts(704,39): error TS2305: Module 'webdriver' has no exported member 'Locator'.
/var/www/wxyz/angular-seed/node_modules/@types/protractor/index.d.ts(725,35): error TS2305: Module 'webdriver' has no exported member 'Locator'.
/var/www/wxyz/angular-seed/node_modules/@types/protractor/index.d.ts(801,48): error TS2305: Module 'webdriver' has no exported member 'Locator'.
/var/www/wxyz/angular-seed/node_modules/@types/protractor/index.d.ts(808,30): error TS2305: Module 'webdriver' has no exported member 'Locator'.
/var/www/wxyz/angular-seed/node_modules/@types/protractor/index.d.ts(1111,32): error TS2305: Module 'webdriver' has no exported member 'Locator'.
/var/www/wxyz/angular-seed/node_modules/@types/protractor/index.d.ts(1139,30): error TS2305: Module 'webdriver' has no exported member 'Locator'.
/var/www/wxyz/angular-seed/node_modules/@types/protractor/index.d.ts(1362,51): error TS2305: Module 'webdriver' has no exported member 'Locator'.
/var/www/wxyz/angular-seed/node_modules/@types/protractor/index.d.ts(1363,42): error TS2305: Module 'webdriver' has no exported member 'Locator'.
/var/www/wxyz/angular-seed/node_modules/@types/protractor/index.d.ts(1364,41): error TS2305: Module 'webdriver' has no exported member 'Locator'.
/var/www/wxyz/angular-seed/node_modules/@types/protractor/index.d.ts(1440,55): error TS2305: Module 'webdriver' has no exported member 'Locator'.
/var/www/wxyz/angular-seed/node_modules/@types/protractor/index.d.ts(1461,60): error TS2305: Module 'webdriver' has no exported member 'Locator'.
/var/www/wxyz/angular-seed/node_modules/@types/protractor/index.d.ts(1477,41): error TS2305: Module 'webdriver' has no exported member 'Locator'.
/var/www/wxyz/angular-seed/node_modules/@types/protractor/index.d.ts(1491,51): error TS2305: Module 'webdriver' has no exported member 'Locator'.
/var/www/wxyz/angular-seed/node_modules/@types/protractor/index.d.ts(1505,58): error TS2305: Module 'webdriver' has no exported member 'Locator'.
/var/www/wxyz/angular-seed/node_modules/@types/protractor/index.d.ts(1574,79): error TS2305: Module 'webdriver' has no exported member 'Locator'.
/var/www/wxyz/angular-seed/node_modules/@types/protractor/index.d.ts(1594,55): error TS2305: Module 'webdriver' has no exported member 'Locator'.
/var/www/wxyz/angular-seed/node_modules/@types/protractor/index.d.ts(1614,36): error TS2305: Module 'webdriver' has no exported member 'Locator'.
[15:27:50] TypeScript: 30 semantic errors
[15:27:50] TypeScript: emit succeeded (with errors)
[15:27:50] Finished 'build.js.dev' after 12 s
[15:27:50] Starting 'build.index.dev'...
[15:27:51] gulp-inject 2 files into index.html.
[15:27:51] gulp-inject 2 files into index.html.
[15:27:51] gulp-inject 1 files into index.html.
[15:27:51] Finished 'build.index.dev' after 790 ms
[15:27:51] Finished 'build.dev' after 16 s
[15:27:51] Starting 'server.start'...
[15:27:52] Finished 'server.start' after 525 ms
[15:27:52] Starting 'watch.dev'...
[15:27:52] Finished 'watch.dev' after 653 ms
[15:27:52] Finished 'serve.dev' after 17 s
[BS] Access URLs:
 -----------------------------------
       Local: http://localhost:5555/
    External: http://10.0.2.15:5555/
 -----------------------------------
          UI: http://localhost:3001
 UI External: http://10.0.2.15:3001
 -----------------------------------
[BS] Serving files from: dist/empty/
(node:19882) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Exited with code 3
```

**Comment by mgechev** [comment]
There are some missing type definitions. Is it a clean clone of the seed or you did some modifications?

**Comment by jarrettj** [comment]
I did an ncu -u. Figured it was that! Deleted and cloned again. No luck. Maybe node, npm version? I'm running npm 3.10.8 and node v6.8.0.

npm start output: 
```
[18:44:12] Requiring external module ts-node/register
[18:44:21] Loading tasks folder /var/www/gobo/angular-seed/tools/tasks/seed
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.assets.dev
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.assets.prod
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.bundle.rxjs
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.bundles.app.exp
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.bundles.app
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.bundles
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.docs
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.html_css
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.index.dev
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.index.prod
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.js.dev
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.js.e2e
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.js.prod.exp
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.js.prod
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.js.test
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.tools
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/check.tools
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/check.versions
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/clean.all
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/clean.coverage
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/clean.dev
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/clean.prod
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/clean.tools
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/clear.files
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/compile.ahead.prod
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/copy.prod
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/e2e
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/generate.manifest
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/karma.run
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/karma.run.with_coverage
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/karma.watch
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/minify.bundles
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/print.banner
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/serve.coverage
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/serve.coverage.watch
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/serve.docs
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/server.prod
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/server.start
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/start.deving
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/tslint
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/watch.dev
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/watch.e2e
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/watch.test
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/webdriver
[18:44:21] Loading tasks folder /var/www/gobo/angular-seed/tools/tasks/project
[18:44:21] Registering task /var/www/gobo/angular-seed/tools/tasks/project/sample.task
[18:44:21] Using gulpfile /var/www/gobo/angular-seed/gulpfile.ts
[18:44:21] Starting 'serve.dev'...
[18:44:21] Starting 'build.dev'...
[18:44:21] Starting 'build.assets.dev'...
[18:44:22] Finished 'build.assets.dev' after 862 ms
[18:44:22] Starting 'build.html_css'...
[18:44:25] Finished 'build.html_css' after 3.49 s
[18:44:25] Starting 'build.js.dev'...
[18:44:38] Finished 'build.js.dev' after 13 s
[18:44:38] Starting 'build.index.dev'...
[18:44:39] gulp-inject 2 files into index.html.
[18:44:39] gulp-inject 2 files into index.html.
[18:44:39] gulp-inject 1 files into index.html.
[18:44:39] Finished 'build.index.dev' after 788 ms
[18:44:39] Finished 'build.dev' after 18 s
[18:44:39] Starting 'server.start'...
[18:44:40] Finished 'server.start' after 542 ms
[18:44:40] Starting 'watch.dev'...
[18:44:40] Finished 'watch.dev' after 660 ms
[18:44:40] Finished 'serve.dev' after 20 s
[BS] Access URLs:
 -----------------------------------
       Local: http://localhost:5555/
    External: http://10.0.2.15:5555/
 -----------------------------------
          UI: http://localhost:3001
 UI External: http://10.0.2.15:3001
 -----------------------------------
[BS] Serving files from: dist/empty/
(node:20427) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Exited with code 3
```

Thanks for the reply.

**Comment by mgechev** [comment]
In `tools/utils/seed/tasks_tools` change `registerTask` to:

```ts
function registerTask(taskname: string, path: string): void {
  const TASK = join(path, taskname);
  util.log('Registering task', util.colors.yellow(tildify(TASK)));

  gulp.task(taskname, (done: any) => {
    const task = normalizeTask(require(TASK), TASK);

    if (changeFileManager.pristine || task.shallRun(changeFileManager.lastChangedFiles)) {
      const res = task.run(done);
      if (typeof res.catch === 'function') {
        res.catch((error: any) => {
          console.error(error);
        });
      }
      return res;
    } else {
      done();
    }
  });
}

```

After that run `npm start` again and share the output.

**Comment by jarrettj** [comment]
Output:

```
[19:06:40] Requiring external module ts-node/register
[19:06:48] Loading tasks folder /var/www/gobo/angular-seed/tools/tasks/seed
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.assets.dev
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.assets.prod
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.bundle.rxjs
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.bundles.app.exp
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.bundles.app
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.bundles
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.docs
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.html_css
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.index.dev
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.index.prod
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.js.dev
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.js.e2e
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.js.prod.exp
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.js.prod
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.js.test
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.tools
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/check.tools
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/check.versions
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/clean.all
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/clean.coverage
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/clean.dev
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/clean.prod
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/clean.tools
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/clear.files
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/compile.ahead.prod
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/copy.prod
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/e2e
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/generate.manifest
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/karma.run
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/karma.run.with_coverage
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/karma.watch
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/minify.bundles
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/print.banner
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/serve.coverage
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/serve.coverage.watch
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/serve.docs
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/server.prod
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/server.start
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/start.deving
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/tslint
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/watch.dev
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/watch.e2e
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/watch.test
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/webdriver
[19:06:48] Loading tasks folder /var/www/gobo/angular-seed/tools/tasks/project
[19:06:48] Registering task /var/www/gobo/angular-seed/tools/tasks/project/sample.task
[19:06:48] Using gulpfile /var/www/gobo/angular-seed/gulpfile.ts
[19:06:48] Starting 'serve.dev'...
[19:06:48] Starting 'build.dev'...
[19:06:48] Starting 'build.assets.dev'...
[19:06:49] Finished 'build.assets.dev' after 757 ms
[19:06:49] Starting 'build.html_css'...
[19:06:51] Finished 'build.html_css' after 2.56 s
[19:06:51] Starting 'build.js.dev'...
[19:07:00] Finished 'build.js.dev' after 8.6 s
[19:07:00] Starting 'build.index.dev'...
[19:07:01] gulp-inject 2 files into index.html.
[19:07:01] gulp-inject 2 files into index.html.
[19:07:01] gulp-inject 1 files into index.html.
[19:07:01] Finished 'build.index.dev' after 1.03 s
[19:07:01] Finished 'build.dev' after 13 s
[19:07:01] Starting 'server.start'...
[19:07:01] Finished 'server.start' after 500 ms
[19:07:01] Starting 'watch.dev'...
[19:07:02] Finished 'watch.dev' after 597 ms
[19:07:02] Finished 'serve.dev' after 14 s
[19:07:02] 'watch.dev' errored after 599 ms
[19:07:02] TypeError: Cannot read property 'catch' of undefined
    at Gulp.<anonymous> (/var/www/gobo/angular-seed/tools/utils/seed/tasks_tools.ts:61:21)
    at module.exports (/var/www/gobo/angular-seed/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/var/www/gobo/angular-seed/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/var/www/gobo/angular-seed/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/var/www/gobo/angular-seed/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/var/www/gobo/angular-seed/node_modules/run-sequence/index.js:86:16)
    at Gulp.onTaskEnd (/var/www/gobo/angular-seed/node_modules/run-sequence/index.js:75:5)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (/var/www/gobo/angular-seed/node_modules/orchestrator/index.js:264:8)
[19:07:02] 'server.start' errored after 1.12 s
[19:07:02] TypeError: Cannot read property 'catch' of undefined
    at Gulp.<anonymous> (/var/www/gobo/angular-seed/tools/utils/seed/tasks_tools.ts:61:21)
    at module.exports (/var/www/gobo/angular-seed/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/var/www/gobo/angular-seed/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/var/www/gobo/angular-seed/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/var/www/gobo/angular-seed/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/var/www/gobo/angular-seed/node_modules/run-sequence/index.js:86:16)
    at Gulp.onTaskEnd (/var/www/gobo/angular-seed/node_modules/run-sequence/index.js:75:5)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (/var/www/gobo/angular-seed/node_modules/orchestrator/index.js:264:8)
[BS] Access URLs:
 -----------------------------------
       Local: http://localhost:5555/
    External: http://10.0.2.15:5555/
 -----------------------------------
          UI: http://localhost:3001
 UI External: http://10.0.2.15:3001
 -----------------------------------
[BS] Serving files from: dist/empty/
(node:20481) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Exited with code 3
```

**Comment by mgechev** [comment]
Lol, okay, update it to:

```
function registerTask(taskname: string, path: string): void {
  const TASK = join(path, taskname);
  util.log('Registering task', util.colors.yellow(tildify(TASK)));

  gulp.task(taskname, (done: any) => {
    const task = normalizeTask(require(TASK), TASK);

    if (changeFileManager.pristine || task.shallRun(changeFileManager.lastChangedFiles)) {
      const res = task.run(done);
      if (res && typeof res.catch === 'function') {
        res.catch((error: any) => {
          console.error(error);
        });
      }
      return res;
    } else {
      done();
    }
  });
}
```

Some tasks return undefined :-)

**Comment by jarrettj** [comment]
```
[19:20:46] Requiring external module ts-node/register
[19:20:54] Loading tasks folder /var/www/gobo/angular-seed/tools/tasks/seed
[19:20:54] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.assets.dev
[19:20:54] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.assets.prod
[19:20:54] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.bundle.rxjs
[19:20:54] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.bundles.app.exp
[19:20:54] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.bundles.app
[19:20:54] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.bundles
[19:20:54] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.docs
[19:20:54] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.html_css
[19:20:54] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.index.dev
[19:20:54] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.index.prod
[19:20:54] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.js.dev
[19:20:54] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.js.e2e
[19:20:54] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.js.prod.exp
[19:20:54] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.js.prod
[19:20:54] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.js.test
[19:20:54] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/build.tools
[19:20:54] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/check.tools
[19:20:54] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/check.versions
[19:20:54] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/clean.all
[19:20:55] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/clean.coverage
[19:20:55] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/clean.dev
[19:20:55] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/clean.prod
[19:20:55] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/clean.tools
[19:20:55] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/clear.files
[19:20:55] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/compile.ahead.prod
[19:20:55] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/copy.prod
[19:20:55] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/e2e
[19:20:55] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/generate.manifest
[19:20:55] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/karma.run
[19:20:55] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/karma.run.with_coverage
[19:20:55] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/karma.watch
[19:20:55] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/minify.bundles
[19:20:55] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/print.banner
[19:20:55] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/serve.coverage
[19:20:55] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/serve.coverage.watch
[19:20:55] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/serve.docs
[19:20:55] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/server.prod
[19:20:55] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/server.start
[19:20:55] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/start.deving
[19:20:55] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/tslint
[19:20:55] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/watch.dev
[19:20:55] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/watch.e2e
[19:20:55] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/watch.test
[19:20:55] Registering task /var/www/gobo/angular-seed/tools/tasks/seed/webdriver
[19:20:55] Loading tasks folder /var/www/gobo/angular-seed/tools/tasks/project
[19:20:55] Registering task /var/www/gobo/angular-seed/tools/tasks/project/sample.task
[19:20:55] Using gulpfile /var/www/gobo/angular-seed/gulpfile.ts
[19:20:55] Starting 'serve.dev'...
[19:20:55] Starting 'build.dev'...
[19:20:55] Starting 'build.assets.dev'...
[19:20:55] Finished 'build.assets.dev' after 736 ms
[19:20:55] Starting 'build.html_css'...
[19:20:58] Finished 'build.html_css' after 2.63 s
[19:20:58] Starting 'build.js.dev'...
[19:21:14] Finished 'build.js.dev' after 16 s
[19:21:14] Starting 'build.index.dev'...
[19:21:15] gulp-inject 2 files into index.html.
[19:21:15] gulp-inject 2 files into index.html.
[19:21:15] gulp-inject 1 files into index.html.
[19:21:15] Finished 'build.index.dev' after 1.44 s
[19:21:15] Finished 'build.dev' after 21 s
[19:21:15] Starting 'server.start'...
[19:21:16] Finished 'server.start' after 568 ms
[19:21:16] Starting 'watch.dev'...
[19:21:17] Finished 'watch.dev' after 863 ms
[19:21:17] Finished 'serve.dev' after 22 s
[BS] Access URLs:
 -----------------------------------
       Local: http://localhost:5555/
    External: http://10.0.2.15:5555/
 -----------------------------------
          UI: http://localhost:3001
 UI External: http://10.0.2.15:3001
 -----------------------------------
[BS] Serving files from: dist/empty/
(node:20692) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Exited with code 3
```

**Comment by jarrettj** [comment]
Hey,

I do think it is my setup. I just cloned https://github.com/start-angular/SB-Admin-BS4-Angular-2 did an npm install, then npm start. It does not live reload as well. And that seems to be based on your boilerplate as well.

The angularjs 2 tour of heroes https://github.com/johnpapa/angular2-tour-of-heroes.git works though.  

I'll figure it out :) Or maybe just downgrade my node and npm versions. Which versions do you recommend?

Thanks for the help though.

JJ

**Comment by mgechev** [comment]
The only difference between the livereload functionality of this project and tour of heroes is the version of `browser-sync` we use. Here we're with newer one. You can try to downgrade it to `^2.12.3` and if it doesn't work the project should be somewhere else.

Good luck! Let me know what you find!
