### ISSUE TITLE
AOT compilation fails

### ISSUE THREAD

**Issue by csreddy** [mgechev/angular-seed#1521]
Gitter seems to be inactive, so please pardon me for posting here

I'm able to `build.prod` fine but `build.prod.exp` is failing. Any help is appreciated.
**env details**
- Mac OSX
- npm@3.10.3
- node@v6.6.0
- tsc@2.0.3

```log
...
...
...
'Object'.
Error at /Users/sreddy/space/angularjs/regression-status/dist/tmp/app/platform/compare.component.ts:90:86: Property 'date' does not exist on type 'Object'.
Error at /Users/sreddy/space/angularjs/regression-status/dist/tmp/app/platform/compare.component.ts:90:99: Property 'diff' does not exist on type 'Object'.
Error at /Users/sreddy/space/angularjs/regression-status/dist/tmp/app/platform/compare.component.ts:112:25: Cannot find name 'CodeMirror'.
Error at /Users/sreddy/space/angularjs/regression-status/dist/tmp/app/platform/platform.reducer.ts:7:7: Type '{ params: {}; status: { data: {}; platforms: undefined[]; }; report: undefined[]; summary: undefi...' is not assignable to type 'IPlatformStatusState'.
  Property 'view' is missing in type '{ params: {}; status: { data: {}; platforms: undefined[]; }; report: undefined[]; summary: undefi...'.
Error at /Users/sreddy/space/angularjs/regression-status/dist/tmp/app/platform/platform.reducer.ts:34:20: Type '{} & { message: string; }' is not assignable to type 'IPlatformStatusState'.
  Property 'view' is missing in type '{} & { message: string; }'.
    at check (/Users/sreddy/space/angularjs/regression-status/node_modules/@angular/tsc-wrapped/src/tsc.js:31:15)
    at Tsc.typeCheck (/Users/sreddy/space/angularjs/regression-status/node_modules/@angular/tsc-wrapped/src/tsc.js:86:9)
    at /Users/sreddy/space/angularjs/regression-status/node_modules/@angular/tsc-wrapped/src/main.js:33:23
    at process._tickCallback (internal/process/next_tick.js:103:7)
Compilation failed
```

**npm-debug.log**
```log
0 info it worked if it ends with ok
1 verbose cli [ '/Users/sreddy/.nvm/versions/node/v6.6.0/bin/node',
1 verbose cli   '/Users/sreddy/.nvm/versions/node/v6.6.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build.prod.exp' ]
2 info using npm@3.10.3
3 info using node@v6.6.0
4 verbose run-script [ 'prebuild.prod.exp', 'build.prod.exp', 'postbuild.prod.exp' ]
5 info lifecycle regression-status@1.0.0~prebuild.prod.exp: regression-status@1.0.0
6 silly lifecycle regression-status@1.0.0~prebuild.prod.exp: no script for prebuild.prod.exp, continuing
7 info lifecycle regression-status@1.0.0~build.prod.exp: regression-status@1.0.0
8 verbose lifecycle regression-status@1.0.0~build.prod.exp: unsafe-perm in lifecycle true
9 verbose lifecycle regression-status@1.0.0~build.prod.exp: PATH: /Users/sreddy/.nvm/versions/node/v6.6.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/sreddy/space/angularjs/regression-status/node_modules/.bin:/Users/sreddy/.nvm/versions/node/v6.6.0/bin:/Users/sreddy/.nvm/versions/node/v6.6.0/bin:/Users/sreddy/.rvm/gems/ruby-2.1.1/bin:/Users/sreddy/.rvm/gems/ruby-2.1.1@global/bin:/Users/sreddy/.rvm/rubies/ruby-2.1.1/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/lib/node_modules:/usr/local/opt/go/libexec/bin:/Users/sreddy/.rvm/bin
10 verbose lifecycle regression-status@1.0.0~build.prod.exp: CWD: /Users/sreddy/space/angularjs/regression-status
11 silly lifecycle regression-status@1.0.0~build.prod.exp: Args: [ '-c', 'gulp build.prod.exp --color --config-env prod' ]
12 silly lifecycle regression-status@1.0.0~build.prod.exp: Returned: code: 1  signal: null
13 info lifecycle regression-status@1.0.0~build.prod.exp: Failed to exec build.prod.exp script
14 verbose stack Error: regression-status@1.0.0 build.prod.exp: `gulp build.prod.exp --color --config-env prod`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/sreddy/.nvm/versions/node/v6.6.0/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/sreddy/.nvm/versions/node/v6.6.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid regression-status@1.0.0
16 verbose cwd /Users/sreddy/space/angularjs/regression-status
17 error Darwin 15.3.0
18 error argv "/Users/sreddy/.nvm/versions/node/v6.6.0/bin/node" "/Users/sreddy/.nvm/versions/node/v6.6.0/bin/npm" "run" "build.prod.exp"
19 error node v6.6.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error regression-status@1.0.0 build.prod.exp: `gulp build.prod.exp --color --config-env prod`
22 error Exit status 1
23 error Failed at the regression-status@1.0.0 build.prod.exp script 'gulp build.prod.exp --color --config-env prod'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the regression-status package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp build.prod.exp --color --config-env prod
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs regression-status
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls regression-status
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by amariniello** [comment]
it's a bit difficult to help you out without a bit of source code..can you at least show the compare.component.ts?

**Comment by csreddy** [comment]
Unfortunately the project is private. Here you go
Please note that I know there are lot of typing errors in many other files to...I just haven't fixed the error however I don't expect the compilation  to fail  as `build.prod` is working fine despite typing errors. Is my assumption wrong ?
```js
import {
    Component,
    OnInit,
    AfterViewInit,
    OnDestroy,
    ChangeDetectionStrategy,
    ChangeDetectorRef
} from '@angular/core';
import { Title } from '@angular/platform-browser';
import {
    DataService,
    EventService,
    ErrorService,
} from '../shared/index';
import {
    Router,
    ActivatedRoute
} from '@angular/router';

//import * as codemirror from 'codemirror';


@Component({
    moduleId: module.id,
    selector: 'compare',
    template: `
    <div class="row">
    <div class="text-center">{{queryParams?.diff}}</div>
    <div class="col-md-6"><h5 class="text-center"><b>Result</b></h5></div>
    <div class="col-md-6"><h5 class="text-center"><b>Key</b></h5></div>
    <div class="text-center"><p class="text-danger">{{message}}</p></div>
    </div>
     <div class="col-md-12" id="diffview"></div>`,
    changeDetection: ChangeDetectionStrategy.OnPush
})



export class CompareComponent implements AfterViewInit, OnDestroy {
    private keyFile: string = '';
    private resultFile: string = '';
    private queryParams: Object;
    private queryParamsSubject$: any;
    private message: string = '';

    constructor(
        private dataService: DataService,
        private eventService: EventService,
        private errorService: ErrorService,
        private router: Router,
        private route: ActivatedRoute,
        private cd: ChangeDetectorRef,
        private titleService: Title
    ) { }

    ngAfterViewInit() {
        this.queryParamsSubject$ = this.route.queryParams.subscribe(
            params => {
                this.queryParams = params;
                if (!params.platform) return;
                if (!params.diff) {
                    // due to a angular bug, put it in timeout function
                    // https://github.com/angular/angular/issues/6005
                    setTimeout(() => {
                        this.message = 'Please select a diff from the dropdown above';
                        this.cd.markForCheck();
                    });
                    this.eventService.announceSpinnerToggle(false);
                    return;
                }
                this.message = '';
                this.getResultAndKeyFile(params);
                this.titleService.setTitle(params.diff);
            }
        );
    }


    getResultAndKeyFile(params: Object) {
        document.getElementById('diffview').innerHTML = '';
        //params.platform = 'linux-64-rh7v-cluster';
        // params.diff = 'bug34600.xml';

        if (!params.platform) return;
        if (!params.diff) return;

        this.keyFile = this.resultFile = ''; // reset after every change
        this.eventService.announceSpinnerToggle(true);
        this.dataService
            .getResultAndKeyFile(params.area, params.branch, params.platform, params.date, params.diff)
            .subscribe(
            data => {
                this.keyFile = data.key;
                this.resultFile = data.result;
            },
            error => this.errorService.handleError(error),
            () => {
                this.showDiffView(this.keyFile, this.resultFile);
                this.cd.markForCheck();
            }
            );
    }


    ngOnDestroy() {
        this.queryParamsSubject$.unsubscribe();
    }

    private showDiffView(key: string, result: string) {
        this.eventService.announceSpinnerToggle(true);
        let element = document.getElementById('diffview');
        let mergeView = CodeMirror.MergeView(element, {
            value: result,
            // origLeft: xml1,
            orig: key,
            lineNumbers: true,
            lineWrapping: true,
            // foldGutter: true,
            // gutters: ['CodeMirror-linenumbers', 'CodeMirror-foldgutter'],
            mode: 'text/xml',
            highlightDifferences: true // false make editable
        });
        this.eventService.announceSpinnerToggle(false);
    }
}
```

**Comment by mgechev** [comment]
This issue doesn't seem like an issue on the project but more like a typing problem that you need to resolve.

**Comment by csreddy** [comment]
I understand it's failing because of typing problem. They are harmless and I want to ignore the error and do the compilation 
Is  AOT compilation not possible by ignoring typing errors ?

**Comment by mgechev** [comment]
You can take a look at the [typescript docs](https://www.typescriptlang.org/docs/tutorial.html). I would not recommend you to ignore them but instead to resolve them.

**Comment by csreddy** [comment]
I have fixed all my type error, but now its failing at main.ts because of `<%= ENV %>` . Please advise.
```
dist/tmp/app/main.ts(11,5): error TS2365: Operator '===' cannot be applied to types '"<%= ENV %>"' and '"prod"'.
dist/tmp/app/main.ts(20,5): error TS2365: Operator '===' cannot be applied to types '"<%= ENV %>"' and '"prod"'.
```
