### ISSUE TITLE
e2e testing failing

### ISSUE THREAD

**Issue by oehm-smith** [mgechev/angular-seed#1541]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting (Nothing solves this)
```

**Current behavior**

Running end to end testing failed.  All three methods I tried fail for different reasons.  See reproduction and OUTPUTS header.

----
(new edit)  I went back to b60150ec5f5b17f615d677b71bce02f99aa58daf (May10) and the testing is failing there also.  I didn't look any further through the history.

**Expected behavior**
e2e.spec tests would be run and succeed / fail accordingly.

**Minimal reproduction of the problem with instructions**

1. Clone repository
2. Run `npm run e2e` or `npm run e2e.ci` or `protractor`

**What is the motivation / use case for changing the behavior?**
I want testing to work

**Please tell us about your environment:**

* **Angular Seed Version:** 2.0.X

1. 2.01
2. current master (4b0183780f0dc24afbad2d19b2b1ee21db475507   Tue Oct 25 13:39:03 2016 -0700)

* **Node:** `node --version` =

1. v5.12.0
2. v6.8.0 both tried

** OUTPUTS **

Using node v6.8.0.

`npm run e2e`

    [nix-shell:~/dev/work/ga/_Angular/angular2-seed]$ npm run e2e

    > angular2-seed@0.0.0 e2e /Users/brookes/dev/work/ga/_Angular/angular2-seed
    > protractor

    [13:41:39] I/direct - Using ChromeDriver directly...
    [13:41:39] I/launcher - Running 1 instances of WebDriver

    /Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/selenium-webdriver/error.js:27
        super(opt_error);
        ^
    SessionNotCreatedError: session not created exception
    from unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"27961.1","isDefault":true},"id":1,"name":"","origin":"://"}
      (Session info: chrome=54.0.2840.71)
      (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Mac OS X 10.12.1 x86_64)
        at WebDriverError (/Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/selenium-webdriver/error.js:27:5)
        at SessionNotCreatedError (/Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/selenium-webdriver/error.js:296:5)
        at Object.checkLegacyResponse (/Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/selenium-webdriver/error.js:580:13)
        at /Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/selenium-webdriver/lib/webdriver.js:64:13
        at Promise.invokeCallback_ (/Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/selenium-webdriver/lib/promise.js:1329:14)
        at TaskQueue.execute_ (/Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/selenium-webdriver/lib/promise.js:2790:14)
        at TaskQueue.executeNext_ (/Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/selenium-webdriver/lib/promise.js:2773:21)
        at asyncRun (/Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/selenium-webdriver/lib/promise.js:2652:27)
        at /Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/selenium-webdriver/lib/promise.js:639:7
        at process._tickCallback (internal/process/next_tick.js:103:7)
    From: Task: WebDriver.createSession()
        at acquireSession (/Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/selenium-webdriver/lib/webdriver.js:62:22)
        at Function.createSession (/Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/selenium-webdriver/lib/webdriver.js:295:12)
        at Driver (/Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/selenium-webdriver/chrome.js:778:38)
        at Direct.getNewDriver (/Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/protractor/built/driverProviders/direct.js:65:26)
        at Runner.createBrowser (/Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/protractor/built/runner.js:182:43)
        at /Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/protractor/built/runner.js:255:30
        at _fulfilled (/Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/q/q.js:834:54)
        at self.promiseDispatch.done (/Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/q/q.js:863:30)
        at Promise.promise.promiseDispatch (/Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/q/q.js:796:13)
        at /Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/q/q.js:556:49
    [13:41:40] E/launcher - Process exited with error code 1

    npm ERR! Darwin 16.1.0
    npm ERR! argv "/nix/store/xj6dkgd4p92k39vpflgq96ka5s6n0zxm-nodejs-6.8.0/bin/node" "/nix/store/hmz1inq8bky8kwxsc15jybgwrk0klmb2-nodejs/bin/npm" "run" "e2e"
    npm ERR! node v6.8.0
    npm ERR! npm  v3.10.8
    npm ERR! code ELIFECYCLE
    npm ERR! angular2-seed@0.0.0 e2e: `protractor`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the angular2-seed@0.0.0 e2e script 'protractor'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the angular2-seed package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     protractor
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs angular2-seed
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls angular2-seed
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/brookes/dev/work/ga/_Angular/angular2-seed/npm-debug.log

`npm run e2e.ci`

    [nix-shell:~/dev/work/ga/_Angular/angular2-seed]$ npm run e2e.ci

    > angular2-seed@0.0.0 e2e.ci /Users/brookes/dev/work/ga/_Angular/angular2-seed
    > gulp build.prod --color && gulp build.js.e2e --color && gulp e2e --color

    [13:42:34] Requiring external module ts-node/register
    [13:42:37] Loading tasks folder /Users/brookes/dev/work/ga/_Angular/angular2-seed/tools/tasks/seed
    [13:42:37] Registering task ~/dev/work/ga/_Angular/angular2-seed/tools/tasks/seed/build.assets.dev
    ...
    [13:42:37] Registering task ~/dev/work/ga/_Angular/angular2-seed/tools/tasks/seed/watch.test
    [13:42:37] Registering task ~/dev/work/ga/_Angular/angular2-seed/tools/tasks/seed/webdriver
    [13:42:37] Loading tasks folder /Users/brookes/dev/work/ga/_Angular/angular2-seed/tools/tasks/project
    [13:42:37] Registering task ~/dev/work/ga/_Angular/angular2-seed/tools/tasks/project/sample.task
    [13:42:37] Using gulpfile ~/dev/work/ga/_Angular/angular2-seed/gulpfile.ts
    [13:42:37] Starting 'build.prod'...
    [13:42:37] Starting 'check.tools'...
    [13:42:37] Tools not compiled, skipping rebuild
    [13:42:37] Finished 'check.tools' after 373 ms
    [13:42:37] Starting 'clean.prod'...
    [13:42:37] Deleted dist/prod
    [13:42:37] Deleted dist/tmp
    [13:42:37] Finished 'clean.prod' after 65 ms
    [13:42:37] Starting 'tslint'...

    /Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/codelyzer/angular/templateParser.js:6
        var TemplateParser = _.TemplateParser;
                              ^
    TypeError: Cannot read property 'TemplateParser' of undefined
        at Object.exports.parseTemplate (/Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/codelyzer/angular/templateParser.js:6:27)
        at InputMetadataWalker.Ng2Walker.visitClassDecorator (/Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/codelyzer/angular/ng2Walker.js:115:62)
        at Array.forEach (native)
        at InputMetadataWalker.Ng2Walker.visitClassDeclaration (/Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/codelyzer/angular/ng2Walker.js:72:40)
        at InputMetadataWalker.SyntaxWalker.visitNode (/Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/tslint/lib/language/walker/syntaxWalker.js:264:22)
        at /Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/tslint/lib/language/walker/syntaxWalker.js:459:63
        at visitEachNode (/Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/typescript/lib/typescript.js:8338:30)
        at Object.forEachChild (/Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/typescript/lib/typescript.js:8498:24)
        at InputMetadataWalker.SyntaxWalker.walkChildren (/Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/tslint/lib/language/walker/syntaxWalker.js:459:12)
        at InputMetadataWalker.SyntaxWalker.visitSourceFile (/Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/tslint/lib/language/walker/syntaxWalker.js:190:14)

    npm ERR! Darwin 16.1.0
    npm ERR! argv "/nix/store/xj6dkgd4p92k39vpflgq96ka5s6n0zxm-nodejs-6.8.0/bin/node" "/nix/store/hmz1inq8bky8kwxsc15jybgwrk0klmb2-nodejs/bin/npm" "run" "e2e.ci"
    npm ERR! node v6.8.0
    npm ERR! npm  v3.10.8
    npm ERR! code ELIFECYCLE
    npm ERR! angular2-seed@0.0.0 e2e.ci: `gulp build.prod --color && gulp build.js.e2e --color && gulp e2e --color`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the angular2-seed@0.0.0 e2e.ci script 'gulp build.prod --color && gulp build.js.e2e --color && gulp e2e --color'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the angular2-seed package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     gulp build.prod --color && gulp build.js.e2e --color && gulp e2e --color
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs angular2-seed
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls angular2-seed
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/brookes/dev/work/ga/_Angular/angular2-seed/npm-debug.log

`protractor`

    [nix-shell:~/dev/work/ga/_Angular/angular2-seed]$ protractor
    [13:43:50] I/direct - Using ChromeDriver directly...
    [13:43:50] I/launcher - Running 1 instances of WebDriver

    /Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/selenium-webdriver/error.js:27
        super(opt_error);
        ^
    SessionNotCreatedError: session not created exception
    from unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"27996.1","isDefault":true},"id":1,"name":"","origin":"://"}
      (Session info: chrome=54.0.2840.71)
      (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Mac OS X 10.12.1 x86_64)
        at WebDriverError (/Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/selenium-webdriver/error.js:27:5)
        at SessionNotCreatedError (/Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/selenium-webdriver/error.js:296:5)
        at Object.checkLegacyResponse (/Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/selenium-webdriver/error.js:580:13)
        at /Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/selenium-webdriver/lib/webdriver.js:64:13
        at Promise.invokeCallback_ (/Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/selenium-webdriver/lib/promise.js:1329:14)
        at TaskQueue.execute_ (/Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/selenium-webdriver/lib/promise.js:2790:14)
        at TaskQueue.executeNext_ (/Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/selenium-webdriver/lib/promise.js:2773:21)
        at asyncRun (/Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/selenium-webdriver/lib/promise.js:2652:27)
        at /Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/selenium-webdriver/lib/promise.js:639:7
        at process._tickCallback (internal/process/next_tick.js:103:7)
    From: Task: WebDriver.createSession()
        at acquireSession (/Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/selenium-webdriver/lib/webdriver.js:62:22)
        at Function.createSession (/Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/selenium-webdriver/lib/webdriver.js:295:12)
        at Driver (/Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/selenium-webdriver/chrome.js:778:38)
        at Direct.getNewDriver (/Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/protractor/built/driverProviders/direct.js:65:26)
        at Runner.createBrowser (/Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/protractor/built/runner.js:182:43)
        at /Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/protractor/built/runner.js:255:30
        at _fulfilled (/Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/q/q.js:834:54)
        at self.promiseDispatch.done (/Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/q/q.js:863:30)
        at Promise.promise.promiseDispatch (/Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/q/q.js:796:13)
        at /Users/brookes/dev/work/ga/_Angular/angular2-seed/node_modules/q/q.js:556:49
    [13:43:51] E/launcher - Process exited with error code 1

**Comment by mgechev** [comment]
We're running e2e tests in CI and the build passes. What's your OS?

**Comment by oehm-smith** [comment]
Cool.  We are currently on release 2.0.1 and I think I must have rooted my checkout to that.

I checked out the head of master and run `npm run build.e2e` and `npm run e2e` and it looked good.  Though the tests seem to be failing as they are failing.  Obviously some things need to be fixed still.  

Do you have an eta for when the next release is expected?  As it seems we should wait until then before sorting our tests out.

**Comment by mgechev** [comment]
In case the issue is not related to the seed we can move the conversation to gitter.

**Comment by oehm-smith** [comment]
Yeah sorry, I thought it was an issue.  Thanks.
