### ISSUE TITLE
Regression: Angular 2.1.2 is breaking AoT build

### ISSUE THREAD

**Issue by irsick** [mgechev/angular-seed#1550]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
After Angular 2.1.2 update 
npm run build.prod.exp

returns this error
```
[23:30:31] 'compile.ahead.prod' errored after 357 ms
[23:30:31] Error: TSError: ⨯ Unable to compile TypeScript
tools/tasks/seed/compile.ahead.prod.ts (14,10): Supplied parameters do not match any signature of call target. (2346)
    at formatError (/Users/irsick/Documents/angular2-seed/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/Users/irsick/Documents/angular2-seed/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/irsick/Documents/angular2-seed/node_modules/orchestrator/index.js:264:8)
    at /Users/irsick/Documents/angular2-seed/node_modules/orchestrator/index.js:275:23
    at finish (/Users/irsick/Documents/angular2-seed/node_modules/orchestrator/lib/runTask.js:21:8)
    at module.exports (/Users/irsick/Documents/angular2-seed/node_modules/orchestrator/lib/runTask.js:36:10)
    at Gulp.Orchestrator._runTask (/Users/irsick/Documents/angular2-seed/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/irsick/Documents/angular2-seed/node_modules/orchestrator/index.js:214:10)
[23:30:31] 'build.prod.exp' errored after 5.92 s
[23:30:31] TSError in plugin 'run-sequence(compile.ahead.prod)'
Message:
    ⨯ Unable to compile TypeScript
tools/tasks/seed/compile.ahead.prod.ts (14,10): Supplied parameters do not match any signature of call target. (2346)
Details:
    diagnostics: [object Object]
Stack:
    at finish (/Users/irsick/Documents/angular2-seed/node_modules/run-sequence/index.js:56:13)
    at Gulp.onError (/Users/irsick/Documents/angular2-seed/node_modules/run-sequence/index.js:67:4)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/irsick/Documents/angular2-seed/node_modules/orchestrator/index.js:264:8)
    at /Users/irsick/Documents/angular2-seed/node_modules/orchestrator/index.js:275:23
    at finish (/Users/irsick/Documents/angular2-seed/node_modules/orchestrator/lib/runTask.js:21:8)
    at module.exports (/Users/irsick/Documents/angular2-seed/node_modules/orchestrator/lib/runTask.js:36:10)
    at Gulp.Orchestrator._runTask (/Users/irsick/Documents/angular2-seed/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/irsick/Documents/angular2-seed/node_modules/orchestrator/index.js:214:10)
```

**Expected behavior**
AoT compilation should complete successfully

**Minimal reproduction of the problem with instructions**

- # git clone angular-seed
- npm install
- npm run build.prod.exp

**What is the motivation / use case for changing the behavior?**
```
$ tsc --project tsconfig.json

14   return CodeGenerator.create(ngOptions, cliOptions, program, host).codegen();
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

tools/tasks/seed/compile.ahead.prod.ts(14,10): error TS2346: Supplied parameters do not match any signature of call target.

```
Even if Angular 2.1.2 packages are not listed explicitly, it's still updated to because of caret (^) version modificator:

```
 npm list | grep @angular

├── @angular/common@2.1.2
├── @angular/compiler@2.1.2
├─┬ @angular/compiler-cli@2.1.2
├── @angular/core@2.1.2
├── @angular/forms@2.1.2
├── @angular/http@2.1.2
├── @angular/platform-browser@2.1.2
├── @angular/platform-browser-dynamic@2.1.2
├─┬ @angular/platform-server@2.1.2
├── @angular/router@3.1.2
├─┬ @angular/tsc-wrapped@0.3.0
```

As a temporary workaround I set up last stable version for Angular packages:
```
  "devDependencies": {
    "@angular/compiler-cli": "2.1.1",
    "@angular/platform-server": "2.1.1"
...
 },
"dependencies": {
    "@angular/common": "2.1.1",
    "@angular/compiler": "2.1.1",
    "@angular/core": "2.1.1",
    "@angular/forms": "2.1.1",
    "@angular/http": "2.1.1",
    "@angular/platform-browser": "2.1.1",
    "@angular/platform-browser-dynamic": "2.1.1",
    "@angular/router": "3.1.1",
...
}


```
**Please tell us about your environment:**
OSX 10.12

* **Angular Seed Version:** 2.0.X
2732677418abf538a269491e7731a8e161c308f4

* **Node:** `node --version` = 6.7.0

**Comment by Delagen** [comment]
provide some options to codegen function

**Comment by irsick** [comment]
Yep, 
`
return CodeGenerator.create(ngOptions, cliOptions, program, host).codegen({transitiveModules: true});`

Added pull request
https://github.com/mgechev/angular-seed/pull/1553

works fine

**Comment by mgechev** [comment]
Fixed by https://github.com/mgechev/angular-seed/pull/1553. @irsick thanks for the PR!
