### ISSUE TITLE
Error in serve.coverage

### ISSUE THREAD

**Issue by karlhaas** [mgechev/angular-seed#1569]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
`npm run serve.coverage` fails with the following error:

```
npm run serve.coverage                                                                                    31.10.2016 15:14:00

> angular-seed@0.0.0 serve.coverage /home/karl/Work/cnc/angular2-seed
> remap-istanbul -b src/ -i coverage/coverage-final.json -o coverage -t html && npm run gulp -- serve.coverage --color

/home/karl/Work/cnc/angular2-seed/node_modules/istanbul/lib/store/memory.js:38
            throw new Error('Unable to find entry for [' + key + ']');
            ^

Error: Unable to find entry for [src/app/app.component.ts]
    at MemoryStore.get (/home/karl/Work/cnc/angular2-seed/node_modules/istanbul/lib/store/memory.js:38:19)
    at HtmlReport.writeDetailPage (/home/karl/Work/cnc/angular2-seed/node_modules/istanbul/lib/report/html.js:411:67)
    at /home/karl/Work/cnc/angular2-seed/node_modules/istanbul/lib/report/html.js:489:26
    at SyncFileWriter.writeFile (/home/karl/Work/cnc/angular2-seed/node_modules/istanbul/lib/util/file-writer.js:57:9)
    at FileWriter.writeFile (/home/karl/Work/cnc/angular2-seed/node_modules/istanbul/lib/util/file-writer.js:147:23)
    at /home/karl/Work/cnc/angular2-seed/node_modules/istanbul/lib/report/html.js:488:24
    at Array.forEach (native)
    at HtmlReport.writeFiles (/home/karl/Work/cnc/angular2-seed/node_modules/istanbul/lib/report/html.js:482:23)
    at /home/karl/Work/cnc/angular2
```
* **Angular Seed Version:**
master dcedc18

* **Node:** `node --version` =6.9.1

**Comment by pete2014** [comment]
Funny thing is that it works if you run through 'npm run start.deving'.
Additionally 'npm test' generates the coverage files in the /coverage folder and if you hook that folder up to a http server you can freely browse the coverage report.

**Comment by karlhaas** [comment]
thx @pete2014 
I compared the two approaches and provided a pull request which solves the problem.
