### ISSUE TITLE
gulp-inline-ng2-template parser error

### ISSUE THREAD

**Issue by ezforms** [mgechev/angular-seed#1586]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
when I run npm run build.prod I get the following build error:

[09:07:24] Finished 'tslint' after 4.48 s
[09:07:24] Starting 'build.assets.prod'...
[09:07:24] Finished 'build.assets.prod' after 231 ms
[09:07:24] Starting 'build.html_css'...
[09:07:26] Finished 'build.html_css' after 1.42 s
[09:07:26] Starting 'copy.prod'...
[09:07:26] Finished 'copy.prod' after 157 ms
[09:07:26] Starting 'build.js.prod'...
[09:07:26] "--config-env" is now deprecated. Use "--env-config" instead.

/Users/robbackus/ezcore-prod-build/node_modules/gulp-inline-ng2-template/parser.js:188
      _urls = eval('({' + frag + '})')[opts.prop_url];
                               ^
SyntaxError: Unexpected end of input
    at replaceFrag (/Users/robbackus/ezcore-prod-build/node_modules/gulp-inline-ng2-template/parser.js:188:32)
    at /Users/robbackus/ezcore-prod-build/node_modules/async/dist/async.js:3845:9
    at replenish (/Users/robbackus/ezcore-prod-build/node_modules/async/dist/async.js:1030:17)
    at iterateeCallback (/Users/robbackus/ezcore-prod-build/node_modules/async/dist/async.js:1015:17)
    at /Users/robbackus/ezcore-prod-build/node_modules/async/dist/async.js:988:16
    at /Users/robbackus/ezcore-prod-build/node_modules/async/dist/async.js:3850:13
    at apply (/Users/robbackus/ezcore-prod-build/node_modules/async/dist/async.js:41:25)
    at /Users/robbackus/ezcore-prod-build/node_modules/async/dist/async.js:76:12
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build.prod"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! angular-seed@0.0.0 build.prod: `gulp build.prod --color --env-config prod --config-env prod --build-type prod`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-seed@0.0.0 build.prod script 'gulp build.prod --color --env-config prod --config-env prod --build-type prod'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build.prod --color --env-config prod --config-env prod --build-type prod
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/robbackus/ezcore-prod-build/npm-debug.log

OSX 10.12.1, WebStorm 2016 r2, node 6.3.1

**Comment by mgechev** [comment]
Hey @ezforms as the error states this is problem in `gulp-inline-ng2-template`, not in the seed. Please search for similar issues in the issue tracker of `gulp-inline-ng2-template` and if you don't find any report it.
