### ISSUE TITLE
npm run build.prod not working

### ISSUE THREAD

**Issue by gustavolira** [mgechev/angular-seed#1594]
Hi,

* **Node:** `node --version` = 5.12.0
* **SO:** = Ubuntu 14.04.5 LTS

ps: What more information can I put to help?

I'm using the last version of branch master and I'm trying to run npm run build.prod but the build is not completing with success.

`myapp/node_modules/@types/protractor/index.d.ts(1844,13): error TS2403: Subsequent variable declarations must have the same type.  Variable '$' must be of type 'JQueryStatic', but here has type 'cssSelectorHelper'.
[10:08:07] TypeScript: 1 semantic error
[10:08:07] TypeScript: emit succeeded (with errors)
`
This is the only error that is happening and unfortunately comes from protractor

If I try use `npm run build.prod.exp` the build finish with error also. The error is:
`[10:18:06] Starting 'compile.ahead.prod'...
Error: undefined, resolving symbol ApplicationModule in /home/gustavo/git/ng2final/ng2final/node_modules/@angular/core/src/application_module.d.ts
    at simplifyInContext (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/static_reflector.ts:532:15)
    at StaticReflector.simplify (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/static_reflector.ts:536:20)
    at StaticReflector.annotations (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/static_reflector.ts:93:28)
    at NgModuleResolver.resolve (/home/gustavo/git/ng2final/ng2final/node_modules/@angular/compiler/bundles/compiler.umd.js:14050:46)
    at CompileMetadataResolver.getNgModuleMetadata (/home/gustavo/git/ng2final/ng2final/node_modules/@angular/compiler/bundles/compiler.umd.js:14296:49)
    at /home/gustavo/git/ng2final/ng2final/node_modules/@angular/compiler/bundles/compiler.umd.js:13284:43
    at Array.forEach (native)
    at _extractModulesAndPipesOrDirectives (/home/gustavo/git/ng2final/ng2final/node_modules/@angular/compiler/bundles/compiler.umd.js:13283:28)
    at analyzeNgModules (/home/gustavo/git/ng2final/ng2final/node_modules/@angular/compiler/bundles/compiler.umd.js:13039:16)
    at OfflineCompiler.compileModules (/home/gustavo/git/ng2final/ng2final/node_modules/@angular/compiler/bundles/compiler.umd.js:13115:20)
Compilation failed
`

**Comment by TheDonDope** [comment]
Hi @gustavolira,

can you please fill out the information in the issue template?  (as seen here: https://github.com/mgechev/angular-seed/issues/new)

Thanks!

P.S.:

The following paragraph is there for a reason :)

```
<!--
IF YOU DON'T FILL OUT THE FOLLOWING INFORMATION WE MIGHT CLOSE YOUR ISSUE WITHOUT INVESTIGATING
-->

```

**Comment by gustavolira** [comment]
Hi @TheDonDope I just edit and put more information, if there is another information that I'm missing, pleas tell me that I will try to put here

**Comment by Nightapes** [comment]
Hi @gustavolira 

Have a look in this issue : #1469

Try following steps:

Possible solution:
1. installed node 6.5.0+
2. re-ran npm install
3. re-ran npm run build.prod.exp

**Comment by mgechev** [comment]
@gustavolira this doesn't look like a seed issue. The AoT is slightly tricky in some cases and you need to make sure that you don't have "dynamic registration of providers", you don't have bindings to private properties and many others.

In order to be able to run the AoT enabled build I'd recommend you to look for similar issues in [angular/issues](https://github.com/angular/angular/issues) and try their [Gitter chat](https://gitter.im/angular/angular).

The Angular team is working on making the AoT much easier and user friendly so hopefully in a couple of months the process will become much less painful!

In case extremely fast initial rendering performance is not a deal-breaker for you, you can save some effort and use `npm run build.prod` instead.

**Comment by gustavolira** [comment]
Hi @mgechev thanks for your attention, I have problem with `npm run build.prod` too, I just tryed with node 5, node 6 and node 7 all without success.
I always receive this error
`/home/gustavo/git/ng2final/ng2final/node_modules/@types/protractor/index.d.ts(1844,13): error TS2403: Subsequent variable declarations must have the same type.  Variable '$' must be of type 'JQueryStatic', but here has type 'cssSelectorHelper'.
[17:11:56] TypeScript: 1 semantic error
[17:11:56] TypeScript: emit succeeded (with errors)`

**Comment by mgechev** [comment]
This is caused by a typing error you have. You can read more about ambient type definitions [here](http://blog.mgechev.com/2016/03/28/ambient-type-definitions-duplicate-identifier-typescript-fix/).
