### ISSUE TITLE
npm install not working 

### ISSUE THREAD

**Issue by agrawal-mohit** [mgechev/angular-seed#1601]
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

This is the error part of the messages on the command line : 

[22:37:06] Loading tasks folder /Users/mohit/work/Angular2/angular-seed/tools/tasks/project
[22:37:06] Registering task ~/work/Angular2/angular-seed/tools/tasks/project/sample.task
[22:37:06] Using gulpfile ~/work/Angular2/angular-seed/gulpfile.ts
[22:37:06] Starting 'print.banner'...
[22:37:06] 'print.banner' errored after 126 ms
[22:37:06] Error: Cannot find module 'supports-color'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at module.exports (/Users/mohit/work/Angular2/angular-seed/tools/tasks/seed/print.banner.ts:8:7)
    at AnonTask.run (/Users/mohit/work/Angular2/angular-seed/tools/utils/seed/tasks_tools.ts:31:18)
    at Gulp.<anonymous> (/Users/mohit/work/Angular2/angular-seed/tools/utils/seed/tasks_tools.ts:60:27)
    at module.exports (/Users/mohit/work/Angular2/angular-seed/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/mohit/work/Angular2/angular-seed/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/mohit/work/Angular2/angular-seed/node_modules/gulp/node_modules/orchestrator/index.js:214:10)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node4-lts/4.5.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! angular-seed@0.0.0 postinstall: `gulp check.versions && gulp build.bundle.rxjs && npm prune && gulp webdriver && gulp print.banner`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-seed@0.0.0 postinstall script 'gulp check.versions && gulp build.bundle.rxjs && npm prune && gulp webdriver && gulp print.banner'.
npm ERR! This is most likely a problem with the angular-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp check.versions && gulp build.bundle.rxjs && npm prune && gulp webdriver && gulp print.banner
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls angular-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mohit/work/Angular2/angular-seed/npm-debug.log

Log file : 
[npm-debug.txt](https://github.com/mgechev/angular-seed/files/572271/npm-debug.txt)

**Expected behavior**
All modules are successfully installed.

**Minimal reproduction of the problem with instructions**
Clone the project, enter the directory and do `npm install` 

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

OS X Yosemite 10.10.5
npm 2.15.9

* **Angular Seed Version:** `0cce180`

* **Node:** `node --version` = 4.5.0

**Comment by mgechev** [comment]
@agrawal-mohit thanks for catching this out! I'm not sure where we lost this dependency...Everything should be fine now!

**Comment by agrawal-mohit** [comment]
works fine, thankyou.
