### ISSUE TITLE
compile.ahead.prod.ts -> TS2346: Supplied parameters do not match any signature of call target

### ISSUE THREAD

**Issue by webia1** [mgechev/angular-seed#1666]
a possible bug ?

![2016-11-24 10_46_aot_prod](https://cloud.githubusercontent.com/assets/2741558/20593739/c8618910-b233-11e6-801e-e528741b8d04.png)

dummy-work-around:

``` javascript
  // return CodeGenerator.create(ngOptions, cliOptions, program, host).codegen({ transitiveModules: true });
  return CodeGenerator.create(ngOptions, cliOptions, program, host).codegen();
```

**Comment by koodikindral** [comment]
npm run build.prod.exp gives following error on win10 (NPM version: 3.10.9 & NodeJS version: 7.2.0):

```
[13:34:32] Error: TSError: ⨯ Unable to compile TypeScript
tools\tasks\seed\compile.ahead.prod.ts (13,10): Supplied parameters do not match any signature of call target. (2346)
    at formatError (C:\Users\gert\angular-seed\node_modules\gulp\bin\gulp.js:169:10)
    at Gulp.<anonymous> (C:\Users\gert\angular-seed\node_modules\gulp\bin\gulp.js:195:15)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (C:\Users\gert\angular-seed\node_modules\orchestrator\index.js:264:8)
    at C:\Users\gert\angular-seed\node_modules\orchestrator\index.js:275:23
    at finish (C:\Users\gert\angular-seed\node_modules\orchestrator\lib\runTask.js:21:8)
    at module.exports (C:\Users\gert\angular-seed\node_modules\orchestrator\lib\runTask.js:36:10)
    at Gulp.Orchestrator._runTask (C:\Users\gert\angular-seed\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Users\gert\angular-seed\node_modules\orchestrator\index.js:214:10)
[13:34:32] 'build.prod.exp' errored after 7.75 s
[13:34:32] TSError in plugin 'run-sequence(compile.ahead.prod)'
Message:
    ⨯ Unable to compile TypeScript
tools\tasks\seed\compile.ahead.prod.ts (13,10): Supplied parameters do not match any signature of call target. (2346)
Details:
    diagnostics: [object Object]
Stack:
    at finish (C:\Users\gert\angular-seed\node_modules\run-sequence\index.js:56:13)
    at Gulp.onError (C:\Users\gert\angular-seed\node_modules\run-sequence\index.js:67:4)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (C:\Users\gert\angular-seed\node_modules\orchestrator\index.js:264:8)
    at C:\Users\gert\angular-seed\node_modules\orchestrator\index.js:275:23
    at finish (C:\Users\gert\angular-seed\node_modules\orchestrator\lib\runTask.js:21:8)
    at module.exports (C:\Users\gert\angular-seed\node_modules\orchestrator\lib\runTask.js:36:10)
    at Gulp.Orchestrator._runTask (C:\Users\gert\angular-seed\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Users\gert\angular-seed\node_modules\orchestrator\index.js:214:10)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build.prod.exp"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! angular-seed@0.0.0 build.prod.exp: `gulp build.prod.exp --color --env-config prod --build-type prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-seed@0.0.0 build.prod.exp script 'gulp build.prod.exp --color --env-config prod --build-type prod'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build.prod.exp --color --env-config prod --build-type prod
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\gert\angular-seed\npm-debug.log
```

**Comment by sfabriece** [comment]
workaround that worked for me: 

change line 13 in compile.ahead.prod.ts to this: 
`return CodeGenerator.create(ngOptions, cliOptions, program, host).codegen({ transitiveModules: true });`

Adding `transitiveModules: true` fixed it for me for the moment.

**Comment by mgechev** [comment]
Fixed in the latest master.
