### ISSUE TITLE
How do I pass angular-cli.json to build.prod.exp

### ISSUE THREAD

**Issue by lzoubek** [mgechev/angular-seed#1711]
Hello, 

I integrate tinymce editor within my application, and build.prod.exp fails for me, because it's unable to locate tinymce module

```
Error at /data/src/SmarterMDM-Admin/GUI_src/dist/tmp/app/shared/components/tinymce.component.ts:44:21: Cannot find name 'TinyMceEditor'.
Error at /data/src/SmarterMDM-Admin/GUI_src/dist/tmp/app/shared/components/tinymce.component.ts:72:5: Cannot find name 'tinymce'.
Error at /data/src/SmarterMDM-Admin/GUI_src/dist/tmp/app/shared/components/tinymce.component.ts:74:9: Cannot find name 'tinymce'.
Error at /data/src/SmarterMDM-Admin/GUI_src/dist/tmp/app/shared/components/tinymce.component.ts:75:7: Cannot find name 'tinymce'.
Error at /data/src/SmarterMDM-Admin/GUI_src/dist/tmp/app/shared/components/tinymce.component.ts:77:7: Cannot find name 'tinymce'.
Error at /data/src/SmarterMDM-Admin/GUI_src/dist/tmp/app/shared/components/tinymce.component.ts:79:36: Cannot find name 'tinymce'.
Error at /data/src/SmarterMDM-Admin/GUI_src/dist/tmp/app/shared/components/tinymce.component.ts:102:7: Cannot find name 'tinymce'.
    at check (/data/src/SmarterMDM-Admin/tools/@angular/tsc-wrapped/src/tsc.ts:43:11)
    at Tsc.typeCheck (/data/src/SmarterMDM-Admin/tools/@angular/tsc-wrapped/src/tsc.ts:104:5)
    at /data/src/SmarterMDM-Admin/tools/@angular/tsc-wrapped/src/main.ts:47:11
    at process._tickCallback (internal/process/next_tick.js:103:7)
Compilation failed

```

According to [TinyMCE docs](https://www.tinymce.com/docs/integrations/angular2/#setuptinymceglobals) I need to add 
tinymce scripts into `angular-cli.json`'s `scripts` section.

I could create `angular-cli.json` with proper content, but how do I tell the `compile.ahead.prod` task, the path to `angular-cli.json`?

Thank you

**Comment by mgechev** [comment]
`angular-cli.json` is a configuration file specific for Angular CLI and this is not Angular CLI.

You can take a look at the project's wiki to get an idea how it works.
