### ISSUE TITLE
Unable to start the application- on Ubuntu 16.04 - Node : 7.2 - NPM - 3.10

### ISSUE THREAD

**Issue by sprakashg** [mgechev/angular-seed#1745]
I cloned the application and did npm install, unable to start the application
Ubuntu 16.04 - Node : 7.2 - NPM - 3.10
Below is the error message
Error: watch /home/suryaprakash/angular-seed-master/src/client ENOSPC
    at exports._errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1305:19)
    at Object.fs.watch (fs.js:1330:11)
    at createFsWatchInstance (/home/suryaprakash/angular-seed-master/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/suryaprakash/angular-seed-master/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/suryaprakash/angular-seed-master/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/suryaprakash/angular-seed-master/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/home/suryaprakash/angular-seed-master/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/home/suryaprakash/angular-seed-master/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:111:15)

npm ERR! Linux 4.4.0-57-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "serve.dev"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! angular-seed@0.0.0 serve.dev: `gulp serve.dev --color --env-config dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-seed@0.0.0 serve.dev script 'gulp serve.dev --color --env-config dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp serve.dev --color --env-config dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/suryaprakash/angular-seed-master/npm-debug.log
![screenshot from 2017-01-05 09-25-06](https://cloud.githubusercontent.com/assets/6829701/21668587/3aee6046-d329-11e6-9723-add5502194f5.png)

**Comment by mgechev** [comment]
ENOSPC means that the drive is full (maybe no space in `tmp`?).

Take a look at this answer in [stackoverflow])http://stackoverflow.com/a/32600959/1106382).

**Comment by sprakashg** [comment]
Thank you
