### ISSUE TITLE
es6 build doesn't work

### ISSUE THREAD

**Issue by mgbee8** [mgechev/angular-seed#1750]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

Trying to run build.dev  for es6 only build, followed instructions for [#1348](https://github.com/mgechev/angular-seed/issues/1348) added "moduleResolution":"node" to src/tsconfig.json 

{
  "compilerOptions": {
    "target": "es6",
    "module": "es6",
    "moduleResolution": "node",
    "declaration": false,
    "removeComments": true,
    "noLib": false,
    "lib": ["es2016", "dom"],
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    "pretty": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitUseStrict": false,
    "noFallthroughCasesInSwitch": true,
    "typeRoots": [
      "../../node_modules/@types",
      "../../node_modules"
    ],
    "types": [
      "node",
      "jasmine",
      "protractor",
      "systemjs"
    ]
  },
  "exclude": [
    "node_modules",
    "dist",
    "src"
  ],
  "compileOnSave": false
}

build throw following error

TypeError: Cannot read property 'status' of null
    at eval (lodash.templateSources[16]:9:15)
    at DestroyableTransform._transform (C:\Users\mb0241\workspace\angular2\plant-at-risk\node_modules\gulp-template\index.js:21:40)
    at DestroyableTransform.Transform._read (C:\Users\mb0241\workspace\angular2\plant-at-risk\node_modules\readable-stream\lib\_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (C:\Users\mb0241\workspace\angular2\plant-at-risk\node_modules\readable-stream\lib\_stream_transform.js:147:83)
    at doWrite (C:\Users\mb0241\workspace\angular2\plant-at-risk\node_modules\readable-stream\lib\_stream_writable.js:347:64)
    at writeOrBuffer (C:\Users\mb0241\workspace\angular2\plant-at-risk\node_modules\readable-stream\lib\_stream_writable.js:336:5)
    at DestroyableTransform.Writable.write (C:\Users\mb0241\workspace\angular2\plant-at-risk\node_modules\readable-stream\lib\_stream_writable.js:274:11)
    at DestroyableTransform.ondata (C:\Users\mb0241\workspace\angular2\plant-at-risk\node_modules\readable-stream\lib\_stream_readable.js:546:20)
    at emitOne (events.js:96:13)
    at DestroyableTransform.emit (events.js:188:7)

**Expected behavior**

expecting es6 build
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

We only need es6 builds have no requirement for backwards compatibility
**Please tell us about your environment:**

Windows 7, VS Code 1.8 node 6.93, npm 3.8.6 
Angular Seed Version:`eb58638`

* **Node:** `node --version` = 6.93

**Comment by mgechev** [comment]
Hey @mgbee8 thanks for giving the project a try. Build target ES6 is not officially supported by the seed project.

Probably sometime in the next a couple of weeks I'll implement this in order to perform bundling with rollup.

Let me know if you have progress with this, otherwise you can put your experiment on a hold until this task pops from my priority queue.

Good luck!

**Comment by ZuSe** [comment]
@mgbee8  @mgechev 

Any news on this? I am also trying my luck on the moment.
