### ISSUE TITLE
cannot build with error 'cannot find name space webdriver'

### ISSUE THREAD

**Issue by tigercosmos** [mgechev/angular-seed#1754]
#

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

I follow
```
git clone --depth 1 https://github.com/mgechev/angular-seed.git
cd angular-seed
npm install
npm run build.prod.aot 
# or
npm run build.prod
```
then cannot build prod and prod.aot with error 'cannot find name space webdriver'
( I didn't change any file)

**Expected behavior**

It should work.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

win 10

* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` = 6.9.2

**log**
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build.prod.aot' ]
2 info using npm@3.10.9
3 info using node@v6.9.2
4 verbose run-script [ 'prebuild.prod.aot', 'build.prod.aot', 'postbuild.prod.aot' ]
5 info lifecycle angular-seed@0.0.0~prebuild.prod.aot: angular-seed@0.0.0
6 silly lifecycle angular-seed@0.0.0~prebuild.prod.aot: no script for prebuild.prod.aot, continuing
7 info lifecycle angular-seed@0.0.0~build.prod.aot: angular-seed@0.0.0
8 verbose lifecycle angular-seed@0.0.0~build.prod.aot: unsafe-perm in lifecycle true
9 verbose lifecycle angular-seed@0.0.0~build.prod.aot: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\Tiger\Desktop\angular-seed\node_modules\.bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\Git\cmd;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin;C:\Windows;C:\msys64\mingw64\bin;C:\msys64\usr\bin;C:\Program Files\MongoDB\Server\3.2\bin;C:\Users\Tiger\AppData\Local\atom\bin;C:\Users\Tiger\AppData\Local\Android\sdk\tools;C:\Users\Tiger\AppData\Local\Android\sdk\platform-tools;C:\php;C:\Program Files\Java\jdk1.8.0_101\bin;C:\Users\Tiger\AppData\Local\Android\sdk\build-tools\24.0.1;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\Tiger\AppData\Roaming\npm;C:\Users\Tiger\AppData\Local\Yarn\.bin
10 verbose lifecycle angular-seed@0.0.0~build.prod.aot: CWD: C:\Users\Tiger\Desktop\angular-seed
11 silly lifecycle angular-seed@0.0.0~build.prod.aot: Args: [ '/d /s /c',
11 silly lifecycle   'gulp build.prod.exp --color --env-config prod --build-type prod' ]
12 silly lifecycle angular-seed@0.0.0~build.prod.aot: Returned: code: 1  signal: null
13 info lifecycle angular-seed@0.0.0~build.prod.aot: Failed to exec build.prod.aot script
14 verbose stack Error: angular-seed@0.0.0 build.prod.aot: `gulp build.prod.exp --color --env-config prod --build-type prod`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid angular-seed@0.0.0
16 verbose cwd C:\Users\Tiger\Desktop\angular-seed
17 error Windows_NT 10.0.10240
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build.prod.aot"
19 error node v6.9.2
20 error npm  v3.10.9
21 error code ELIFECYCLE
22 error angular-seed@0.0.0 build.prod.aot: `gulp build.prod.exp --color --env-config prod --build-type prod`
22 error Exit status 1
23 error Failed at the angular-seed@0.0.0 build.prod.aot script 'gulp build.prod.exp --color --env-config prod --build-type prod'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular-seed package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp build.prod.exp --color --env-config prod --build-type prod
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular-seed
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular-seed
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by lifaon74** [comment]
Working on it

**Comment by lifaon74** [comment]
Don't forget to remove it on github ;)

**Comment by mgechev** [comment]
I removed that a few days ago https://github.com/mgechev/angular-seed/commit/87c68699cd4cb6ce5ba4d21dff3454e849695a51.

**Comment by tigercosmos** [comment]
Thanks!
