### ISSUE TITLE
build.prod using Visual Studio Online errors

### ISSUE THREAD

**Issue by bwwilliam** [mgechev/angular-seed#1813]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

I received lots of errors using Visual studio TFS Online by "npm run build.prod"
However, if I use the same command to run on my local machine, the command works fine. 
`2017-02-13T02:32:58.8680480Z 
2017-02-13T02:33:00.8950477Z [[90m02:33:00[39m] '[36mtslint[39m' [31merrored after[39m [35m5.19 s[39m
2017-02-13T02:33:00.8950477Z [[90m02:33:00[39m] [31mError[39m in plugin '[36mgulp-tslint[39m'
2017-02-13T02:33:00.9000482Z Message:
2017-02-13T02:33:00.9000482Z     Failed to lint: src/client/app/app.module.ts [16, 1]: space indentation expected, src/client/app/app.module.ts [15, 70]: trailing whitespace, src/client/app/app.module.ts [19, 28]: trailing whitespace, src/client/app/about/about.component.ts [21, 17]: block is empty, src/client/app/about/about.component.ts [12, 48]: trailing whitespace, src/client/app/about/about.component.ts [26, 15]: trailing whitespace, src/client/app/account/account-routing.module.ts [15, 37]: file should end with a newline, src/client/app/account/account.component.ts [21, 2]: file should end with a newline, src/client/app/account/account.component.ts [14, 5]: Declaration of public instance member variable not allowed to appear after declaration of public instance member function, src/client/app/account/account.component.ts [10, 50]: trailing whitespace, src/client/app/account/account.component.ts [2, 59]: Missing semicolon, src/client/app/account/account.module.ts [13, 30]: file should end with a newline, src/client/app/account/account.module.ts [9, 33]: trailing whitespace, src/client/app/home/home.component.ts [17, 1]: trailing whitespace, src/client/app/home/home.component.ts [31, 1]: trailing whitespace, src/client/app/login/login.component.ts [39, 2]: file should end with a newline, src/client/app/login/login.component.ts [30, 22]: block is empty, src/client/app/login/login.component.ts [17, 116]: trailing whitespace, src/client/app/login/login.component.ts [38, 1]: trailing whitespace, src/client/app/login/login.component.ts [20, 15]: missing whitespace, src/client/app/login/login.component.ts [24, 12]: missing whitespace, src/client/app/login/login.component.ts [30, 17]: misplaced 'else', src/client/app/login/login.component.ts [14, 21]: " should be ', src/client/app/login/login.component.ts [15, 22]: " should be ', src/client/app/login/login.component.ts [27, 28]: == should be ===, src/client/app/shared/index.ts [11, 37]: file should end with a newline, src/client/app/shared/account/account.service.ts [29, 1]: trailing whitespace, src/client/app/shared/account/account.service.ts [27, 25]: " should be ', src/client/app/shared/account/account.service.ts [27, 41]: " should be ', src/client/app/shared/account/account.service.ts [28, 25]: " should be ', src/client/app/shared/account/account.service.ts [28, 42]: " should be ', src/client/app/shared/guard/auth.guard.ts [18, 2]: file should end with a newline, src/client/app/shared/guard/auth.guard.ts [6, 1]: trailing whitespace, src/client/app/shared/guard/auth.guard.ts [8, 1]: trailing whitespace, src/client/app/shared/guard/auth.guard.ts [11, 41]: missing whitespace, src/client/app/shared/guard/index.ts [4, 30]: file should end with a newline, src/client/app/shared/models/Account.ts [4, 2]: file should end with a newline, src/client/app/shared/models/Account.ts [3, 21]: trailing whitespace, src/client/app/shared/models/index.ts [6, 24]: file should end with a newline, src/client/app/shared/models/Jwt.ts [8, 2]: file should end with a newline, src/client/app/shared/models/Jwt.ts [6, 18]: trailing whitespace, src/client/app/shared/models/User.ts [6, 2]: file should end with a newline, src/client/app/shared/navbar/navbar.component.ts [19, 15]: block is empty, src/client/app/shared/navbar/navbar.component.ts [2, 56]: trailing whitespace, src/client/app/shared/navbar/navbar.component.ts [20, 1]: trailing whitespace, src/client/app/shared/navbar/navbar.component.ts [23, 1]: trailing whitespace, src/client/app/shared/navbar/navbar.component.ts [16, 89]: missing whitespace, src/client/app/shared/navbar/navbar.component.ts [19, 15]: missing whitespace, src/client/app/shared/navbar/navbar.component.html [1, 2]: You can bind only to public class members., src/client/app/shared/navbar/navbar.component.html [1, 1]: You can bind only to public class members., src/client/app/shared/user/user.service.spec.ts [39, 1]: Exceeds maximum line length of 140, src/client/app/shared/user/user.service.ts [32, 1]: Exceeds maximum line length of 140, src/client/app/shared/user/user.service.ts [14, 3]: Declaration of public instance member variable not allowed to appear after declaration of private instance member variable, src/client/app/shared/user/user.service.ts [40, 9]: misplaced 'else', src/client/app/shared/user/user.service.ts [30, 25]: " should be ', src/client/app/shared/user/user.service.ts [30, 41]: " should be ', src/client/app/shared/user/user.service.ts [32, 44]: " should be ', src/client/app/shared/user/user.service.ts [37, 32]: " should be ', src/client/app/shared/user/user.service.ts [62, 53]: " should be ', src/client/app/shared/user/user.service.ts [50, 13]: == should be ===, tools/config/seed.config.ts [365, 1]: Exceeds maximum line length of 140, tools/config/seed.config.ts [314, 1]: trailing whitespace, tools/config/seed.config.ts [374, 1]: trailing whitespace.
2017-02-13T02:33:00.9000482Z [[90m02:33:00[39m] '[36mbuild.prod[39m' [31merrored after[39m [35m5.71 s[39m
2017-02-13T02:33:00.9000482Z [[90m02:33:00[39m] [31mError[39m in plugin '[36mrun-sequence(tslint)[39m'
2017-02-13T02:33:00.9000482Z Message:
2017-02-13T02:33:00.9010488Z     Failed to lint: src/client/app/app.module.ts [16, 1]: space indentation expected, src/client/app/app.module.ts [15, 70]: trailing whitespace, src/client/app/app.module.ts [19, 28]: trailing whitespace, src/client/app/about/about.component.ts [21, 17]: block is empty, src/client/app/about/about.component.ts [12, 48]: trailing whitespace, src/client/app/about/about.component.ts [26, 15]: trailing whitespace, src/client/app/account/account-routing.module.ts [15, 37]: file should end with a newline, src/client/app/account/account.component.ts [21, 2]: file should end with a newline, src/client/app/account/account.component.ts [14, 5]: Declaration of public instance member variable not allowed to appear after declaration of public instance member function, src/client/app/account/account.component.ts [10, 50]: trailing whitespace, src/client/app/account/account.component.ts [2, 59]: Missing semicolon, src/client/app/account/account.module.ts [13, 30]: file should end with a newline, src/client/app/account/account.module.ts [9, 33]: trailing whitespace, src/client/app/home/home.component.ts [17, 1]: trailing whitespace, src/client/app/home/home.component.ts [31, 1]: trailing whitespace, src/client/app/login/login.component.ts [39, 2]: file should end with a newline, src/client/app/login/login.component.ts [30, 22]: block is empty, src/client/app/login/login.component.ts [17, 116]: trailing whitespace, src/client/app/login/login.component.ts [38, 1]: trailing whitespace, src/client/app/login/login.component.ts [20, 15]: missing whitespace, src/client/app/login/login.component.ts [24, 12]: missing whitespace, src/client/app/login/login.component.ts [30, 17]: misplaced 'else', src/client/app/login/login.component.ts [14, 21]: " should be ', src/client/app/login/login.component.ts [15, 22]: " should be ', src/client/app/login/login.component.ts [27, 28]: == should be ===, src/client/app/shared/index.ts [11, 37]: file should end with a newline, src/client/app/shared/account/account.service.ts [29, 1]: trailing whitespace, src/client/app/shared/account/account.service.ts [27, 25]: " should be ', src/client/app/shared/account/account.service.ts [27, 41]: " should be ', src/client/app/shared/account/account.service.ts [28, 25]: " should be ', src/client/app/shared/account/account.service.ts [28, 42]: " should be ', src/client/app/shared/guard/auth.guard.ts [18, 2]: file should end with a newline, src/client/app/shared/guard/auth.guard.ts [6, 1]: trailing whitespace, src/client/app/shared/guard/auth.guard.ts [8, 1]: trailing whitespace, src/client/app/shared/guard/auth.guard.ts [11, 41]: missing whitespace, src/client/app/shared/guard/index.ts [4, 30]: file should end with a newline, src/client/app/shared/models/Account.ts [4, 2]: file should end with a newline, src/client/app/shared/models/Account.ts [3, 21]: trailing whitespace, src/client/app/shared/models/index.ts [6, 24]: file should end with a newline, src/client/app/shared/models/Jwt.ts [8, 2]: file should end with a newline, src/client/app/shared/models/Jwt.ts [6, 18]: trailing whitespace, src/client/app/shared/models/User.ts [6, 2]: file should end with a newline, src/client/app/shared/navbar/navbar.component.ts [19, 15]: block is empty, src/client/app/shared/navbar/navbar.component.ts [2, 56]: trailing whitespace, src/client/app/shared/navbar/navbar.component.ts [20, 1]: trailing whitespace, src/client/app/shared/navbar/navbar.component.ts [23, 1]: trailing whitespace, src/client/app/shared/navbar/navbar.component.ts [16, 89]: missing whitespace, src/client/app/shared/navbar/navbar.component.ts [19, 15]: missing whitespace, src/client/app/shared/navbar/navbar.component.html [1, 2]: You can bind only to public class members., src/client/app/shared/navbar/navbar.component.html [1, 1]: You can bind only to public class members., src/client/app/shared/user/user.service.spec.ts [39, 1]: Exceeds maximum line length of 140, src/client/app/shared/user/user.service.ts [32, 1]: Exceeds maximum line length of 140, src/client/app/shared/user/user.service.ts [14, 3]: Declaration of public instance member variable not allowed to appear after declaration of private instance member variable, src/client/app/shared/user/user.service.ts [40, 9]: misplaced 'else', src/client/app/shared/user/user.service.ts [30, 25]: " should be ', src/client/app/shared/user/user.service.ts [30, 41]: " should be ', src/client/app/shared/user/user.service.ts [32, 44]: " should be ', src/client/app/shared/user/user.service.ts [37, 32]: " should be ', src/client/app/shared/user/user.service.ts [62, 53]: " should be ', src/client/app/shared/user/user.service.ts [50, 13]: == should be ===, tools/config/seed.config.ts [365, 1]: Exceeds maximum line length of 140, tools/config/seed.config.ts [314, 1]: trailing whitespace, tools/config/seed.config.ts [374, 1]: trailing whitespace.
2017-02-13T02:33:00.9010488Z Stack:
2017-02-13T02:33:00.9010488Z     at finish (D:\a\1\s\node_modules\run-sequence\index.js:56:13)
2017-02-13T02:33:00.9010488Z     at Gulp.onError (D:\a\1\s\node_modules\run-sequence\index.js:67:4)
2017-02-13T02:33:00.9010488Z     at emitOne (events.js:101:20)
2017-02-13T02:33:00.9010488Z     at Gulp.emit (events.js:188:7)
2017-02-13T02:33:00.9010488Z     at Gulp.Orchestrator._emitTaskDone (D:\a\1\s\node_modules\orchestrator\index.js:264:8)
2017-02-13T02:33:00.9010488Z     at D:\a\1\s\node_modules\orchestrator\index.js:275:23
2017-02-13T02:33:00.9010488Z     at finish (D:\a\1\s\node_modules\orchestrator\lib\runTask.js:21:8)
2017-02-13T02:33:00.9010488Z     at Stream.<anonymous> (D:\a\1\s\node_modules\orchestrator\lib\runTask.js:52:4)
2017-02-13T02:33:00.9010488Z     at Stream.f (D:\a\1\s\node_modules\end-of-stream\node_modules\once\once.js:17:25)
2017-02-13T02:33:00.9010488Z     at emitOne (events.js:101:20)
2017-02-13T02:33:01.0141363Z 
2017-02-13T02:33:01.0141363Z npm ERR! Windows_NT 6.3.9600
2017-02-13T02:33:01.0160476Z npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build.prod"
2017-02-13T02:33:01.0160476Z npm ERR! node v6.9.1
2017-02-13T02:33:01.0160476Z npm ERR! npm  v3.10.8
2017-02-13T02:33:01.0160476Z npm ERR! code ELIFECYCLE
2017-02-13T02:33:01.0160476Z npm ERR! angular-seed@0.0.0 build.prod: `gulp build.prod --color --env-config prod --build-type prod`
2017-02-13T02:33:01.0160476Z npm ERR! Exit status 1
2017-02-13T02:33:01.0160476Z npm ERR! 
2017-02-13T02:33:01.0160476Z npm ERR! Failed at the angular-seed@0.0.0 build.prod script 'gulp build.prod --color --env-config prod --build-type prod'.
2017-02-13T02:33:01.0170468Z npm ERR! Make sure you have the latest version of node.js and npm installed.
2017-02-13T02:33:01.0170468Z npm ERR! If you do, this is most likely a problem with the angular-seed package,
2017-02-13T02:33:01.0170468Z npm ERR! not with npm itself.
2017-02-13T02:33:01.0170468Z npm ERR! Tell the author that this fails on your system:
2017-02-13T02:33:01.0170468Z npm ERR!     gulp build.prod --color --env-config prod --build-type prod
2017-02-13T02:33:01.0170468Z npm ERR! You can get information on how to open an issue for this project with:
2017-02-13T02:33:01.0170468Z npm ERR!     npm bugs angular-seed
2017-02-13T02:33:01.0170468Z npm ERR! Or if that isn't available, you can get their info via:
2017-02-13T02:33:01.0170468Z npm ERR!     npm owner ls angular-seed
2017-02-13T02:33:01.0170468Z npm ERR! There is likely additional logging output above.
2017-02-13T02:33:01.0170468Z 
2017-02-13T02:33:01.0170468Z npm ERR! Please include the following file with any support request:`
**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

To achieve CI
**Please tell us about your environment:**

* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` = 6.9

**Comment by bwwilliam** [comment]
I also tried to clone the latest version from github and pushed up to Visual studio online, but still failed with the PROD build. I could grant you the access if you want to see what's happening. 

Thank you.

**Comment by bwwilliam** [comment]
Any help will be appreciated, I have been working on this for a whole day.

**Comment by skolli853780** [comment]
you are getting the error because of tslint

go to tools - config - seed.tasks.json

you have 2 options.. 

1) fix all the errors 
2) comment out the tslint

  "build.prod": [
    "check.tools",
    "clean.prod",
    "tslint",

**Comment by skolli853780** [comment]
I would recommend option 1 as tslint is used to follow best practices with typescript

**Comment by bwwilliam** [comment]
Thank you for the reply. 
I would also prefer option 1, but any idea how I can actually fix the errors?

**Comment by bwwilliam** [comment]
This is an issue/bug why is it closed?

**Comment by mgechev** [comment]
It is not an issue. As @skolli853780 mentioned, tslint found style problems in your code. 
Take a look at https://palantir.github.io/tslint/ for more details.

**Comment by bwwilliam** [comment]
@mgechev , but the same problem also happens when I hook the build directly to this project on github in Visual Studio Team Services. i.e. I configured the build to pull directly from this repo, and run the steps.

**Comment by mgechev** [comment]
The build passes on windows (AppVeyor), which means that the code in the repository doesn't contain any linting errors. Probably in your custom code you introduced them. You can either:

- Fix them.
- Introduce custom guidelines for your project (i.e. update tslint.json).
- Disable tslint.

All three options require you to get familiar with tslint and have basic understanding of the build process. I'd recommend you to take a look at the documentation and see how to proceed.

**Comment by bwwilliam** [comment]
Thanks for all your help @mgechev  and @skolli853780 The problem is fixed now by meeting all the tslint rules. 
For anyone who has the same problem, either turn off the rule which is not recommended or go back to fix the code to meet tslint rules which can be found at https://palantir.github.io/tslint/rules/
