### ISSUE TITLE
Uncaught ReferenceError: require is not defined at angular2-jwt.ts

### ISSUE THREAD

**Issue by ahmadqarshi** [mgechev/angular-seed#1833]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
I cloned the latest angular-seed repository, ran it and it worked. Then I followed the instruction for [Add External Dependency](https://github.com/mgechev/angular-seed/wiki/Add-external-dependency). I followed the `Full Example`. When I started application I saw below console logs:

    angular2-jwt.js:19 Uncaught ReferenceError: require is not defined
        at angular2-jwt.js:19
    :5555/node_modules/@angular/core/bundles/core.umd.js:3064 EXCEPTION: obj.hasOwnProperty is not a function
    ErrorHandler.handleError @ :5555/node_modules/@angular/core/bundles/core.umd.js:3064
    :5555/node_modules/@angular/core/bundles/core.umd.js:3069 ORIGINAL STACKTRACE:
    ErrorHandler.handleError @ :5555/node_modules/@angular/core/bundles/core.umd.js:3069
    :5555/node_modules/@angular/core/bundles/core.umd.js:3070 TypeError: obj.hasOwnProperty is not a function
        at setValueOnPath (http://localhost:5555/node_modules/@angular/platform-browser/bundles/platform-browser.umd.js:135:21)
        at BrowserDomAdapter.setGlobalVar (http://localhost:5555/node_modules/@angular/platform-browser/bundles/platform-browser.umd.js:2190:77)
        at _createRootRenderer (http://localhost:5555/node_modules/@angular/platform-browser/bundles/platform-browser.umd.js:3333:18)
        at _createConditionalRootRenderer (http://localhost:5555/node_modules/@angular/platform-browser/bundles/platform-browser.umd.js:3324:13)
        at AppModuleInjector.get (/AppModule/module.ngfactory.js:80:69)
        at AppModuleInjector.get (/AppModule/module.ngfactory.js:100:87)
        at AppModuleInjector.getInternal (/AppModule/module.ngfactory.js:315:49)
        at AppModuleInjector.NgModuleInjector.get (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:8490:48)
        at ComponentFactory.create (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:7283:48)
        at ApplicationRef_.bootstrap (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:8257:61)
        at eval (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:8093:93)
        at Array.forEach (native)
        at PlatformRef_._moduleDoBootstrap (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:8093:46)
        at eval (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:8045:31)
        at ZoneDelegate.invoke (http://localhost:5555/node_modules/zone.js/dist/zone.js?1487863689070:330:26)
    ErrorHandler.handleError @ :5555/node_modules/@angular/core/bundles/core.umd.js:3070
    zone.js:516 Unhandled Promise rejection: obj.hasOwnProperty is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: obj.hasOwnProperty is not a function
        at setValueOnPath (http://localhost:5555/node_modules/@angular/platform-browser/bundles/platform-browser.umd.js:135:21)
        at BrowserDomAdapter.setGlobalVar (http://localhost:5555/node_modules/@angular/platform-browser/bundles/platform-browser.umd.js:2190:77)
        at _createRootRenderer (http://localhost:5555/node_modules/@angular/platform-browser/bundles/platform-browser.umd.js:3333:18)
        at _createConditionalRootRenderer (http://localhost:5555/node_modules/@angular/platform-browser/bundles/platform-browser.umd.js:3324:13)
        at AppModuleInjector.get (/AppModule/module.ngfactory.js:80:69)
        at AppModuleInjector.get (/AppModule/module.ngfactory.js:100:87)
        at AppModuleInjector.getInternal (/AppModule/module.ngfactory.js:315:49)
        at AppModuleInjector.NgModuleInjector.get (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:8490:48)
        at ComponentFactory.create (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:7283:48)
        at ApplicationRef_.bootstrap (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:8257:61)
        at eval (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:8093:93)
        at Array.forEach (native)
        at PlatformRef_._moduleDoBootstrap (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:8093:46)
        at eval (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:8045:31)
        at ZoneDelegate.invoke (http://localhost:5555/node_modules/zone.js/dist/zone.js?1487863689070:330:26) TypeError: obj.hasOwnProperty is not a function
        at setValueOnPath (http://localhost:5555/node_modules/@angular/platform-browser/bundles/platform-browser.umd.js:135:21)
        at BrowserDomAdapter.setGlobalVar (http://localhost:5555/node_modules/@angular/platform-browser/bundles/platform-browser.umd.js:2190:77)
        at _createRootRenderer (http://localhost:5555/node_modules/@angular/platform-browser/bundles/platform-browser.umd.js:3333:18)
        at _createConditionalRootRenderer (http://localhost:5555/node_modules/@angular/platform-browser/bundles/platform-browser.umd.js:3324:13)
        at AppModuleInjector.get (/AppModule/module.ngfactory.js:80:69)
        at AppModuleInjector.get (/AppModule/module.ngfactory.js:100:87)
        at AppModuleInjector.getInternal (/AppModule/module.ngfactory.js:315:49)
        at AppModuleInjector.NgModuleInjector.get (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:8490:48)
        at ComponentFactory.create (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:7283:48)
        at ApplicationRef_.bootstrap (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:8257:61)
        at eval (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:8093:93)
        at Array.forEach (native)
        at PlatformRef_._moduleDoBootstrap (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:8093:46)
        at eval (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:8045:31)
        at ZoneDelegate.invoke (http://localhost:5555/node_modules/zone.js/dist/zone.js?1487863689070:330:26)
    consoleError @ zone.js:516
    zone.js:518 ZoneAwareError
    consoleError @ zone.js:518

By the way, the instructions in the WIKI page mentioned above seem to be very old and need to be updated. Furthermore, after running `npm install` node-modules folder contains 838 directories which seems odd.

**Expected behavior**
Should not display any error in the console.

**Please tell us about your environment:**
Windows 10 Pro
VS Code

* **Angular Seed Version:** `365f0ecade4bea45e81d311889f4ed9a2a18d35b`

* **Node:** `node --version` = 6.9.5
* **NPM:** 3.10.10

**Comment by mgechev** [comment]
I updated the [Wiki](https://github.com/mgechev/angular-seed/wiki/Add-external-dependency), not an issue in the seed.

> Furthermore, after running npm install node-modules folder contains 838 directories which seems odd.

Why is this odd?

**Comment by ahmadqarshi** [comment]
Thanks @mgechev that did the trick.

> Why is this odd?

Actually, we had this issue in the past where `npm install` started corrupting the directory structure on one of our development machine and instead of creating 30 or so directories inside node_modules, it was creating 600+ directories. We finally resolved it by recreating the Windows user profile.

So I thought may be its something similar.
