### ISSUE TITLE
build.prod.rollup.aot throws an error (on a fresh git clone)

### ISSUE THREAD

**Issue by alarive** [mgechev/angular-seed#1840]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
```

I cannot get build.prod.rollup.aot to work.

```
git clone https://github.com/mgechev/angular-seed
cd angular-seed
npm install
npm run build.prod.rollup.aot
```

It throws the following error
```
{ Error: Unexpected token
    at error (/home/alarive/angular-seed/node_modules/rollup/src/utils/error.js:2:14)
    at Module.error$1 [as error] (/home/alarive/angular-seed/node_modules/rollup/src/Module.js:303:2)
    at tryParse (/home/alarive/angular-seed/node_modules/rollup/src/Module.js:27:10)
    at new Module (/home/alarive/angular-seed/node_modules/rollup/src/Module.js:53:15)
    at /home/alarive/angular-seed/node_modules/rollup/src/Bundle.js:301:20
  code: 'PARSE_ERROR',
  pos: 92,
  loc: 
   { file: '/home/alarive/angular-seed/node_modules/rxjs/util/isArrayLike.js',
     line: 2,
     column: 78 },
  frame: '1: "use strict";\n2: var isArrayLike_1 = function (x) { return x && typeof x.length === \'number\'; });\n    
```

npm version : 3.10.10
node version : v6.10.0

**Comment by rikup88** [comment]
Same here. Mac OS 10.11.6, npm 3.10.9, node 6.9.2.

**Comment by rikup88** [comment]
Reverting RxJS to version 5.1.1 or earlier removed the error and the build succeeded.

**Comment by mgechev** [comment]
Reverted back temporary.

**Comment by alarive** [comment]
I can confirm it is working well with this version of RxJS.

**Comment by mgechev** [comment]
It's an issue in the commonjs plugin for rollup https://github.com/rollup/rollup-plugin-commonjs/issues/168.
