### ISSUE TITLE
There is an error when trying to run e2e tests on a fresh clone

### ISSUE THREAD

**Issue by lobo-tuerto** [mgechev/angular-seed#1853]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
After running 
When running `npm run e2e` you can see this:
```
$ npm run e2e

> angular-seed@0.0.0 e2e /home/x/desarrollo/proyectos/angular2/angular-seed
> protractor

(node:29827) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[21:41:42] I/direct - Using ChromeDriver directly...
[21:41:42] I/launcher - Running 1 instances of WebDriver
[21:41:42] E/direct - Error code: 135
[21:41:42] E/direct - Error message: Could not find chromedriver at /home/x/desarrollo/proyectos/angular2/angular-seed/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.26. Run 'webdriver-manager update' to download binaries.
[21:41:42] E/direct - Error: Could not find chromedriver at /home/x/desarrollo/proyectos/angular2/angular-seed/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.26. Run 'webdriver-manager update' to download binaries.
    at BrowserError.IError [as constructor] (/home/x/desarrollo/proyectos/angular2/angular-seed/node_modules/protractor/built/exitCodes.js:13:23)
    at BrowserError.ProtractorError [as constructor] (/home/x/desarrollo/proyectos/angular2/angular-seed/node_modules/protractor/built/exitCodes.js:21:28)
    at new BrowserError (/home/x/desarrollo/proyectos/angular2/angular-seed/node_modules/protractor/built/exitCodes.js:67:23)
    at Direct.getNewDriver (/home/x/desarrollo/proyectos/angular2/angular-seed/node_modules/protractor/built/driverProviders/direct.js:66:27)
    at Runner.createBrowser (/home/x/desarrollo/proyectos/angular2/angular-seed/node_modules/protractor/built/runner.js:198:43)
    at /home/x/desarrollo/proyectos/angular2/angular-seed/node_modules/protractor/built/runner.js:277:30
    at _fulfilled (/home/x/desarrollo/proyectos/angular2/angular-seed/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/x/desarrollo/proyectos/angular2/angular-seed/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/x/desarrollo/proyectos/angular2/angular-seed/node_modules/q/q.js:796:13)
    at /home/x/desarrollo/proyectos/angular2/angular-seed/node_modules/q/q.js:556:49
[21:41:42] E/launcher - Process exited with error code 135

npm ERR! Linux 4.4.0-65-generic
npm ERR! argv "/home/x/.nvm/versions/node/v7.7.1/bin/node" "/home/x/.nvm/versions/node/v7.7.1/bin/npm" "run" "e2e"
npm ERR! node v7.7.1
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! angular-seed@0.0.0 e2e: `protractor`
npm ERR! Exit status 135
npm ERR! 
npm ERR! Failed at the angular-seed@0.0.0 e2e script 'protractor'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     protractor
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/x/desarrollo/proyectos/angular2/angular-seed/npm-debug.log
```

**Expected behavior**
There should be no errors on a fresh clone.

**Minimal reproduction of the problem with instructions**
`git clone`, `yarn install`
```
# npm install webdriver-manager <- Install this first for e2e testing
# npm run webdriver-update <- You will need to run this the first time
$ npm run webdriver-start #terminal 1
$ npm run serve.e2e #terminal 2
$ npm run e2e #terminal 3
```

**Please tell us about your environment:**
Node: v7.7.1
NPM: 4.1.2
SO: Ubuntu 16.04

* **Angular Seed Version:** `8bfec1a`

* **Node:** `node --version` =v7.7.1

**Comment by mgechev** [comment]
Thanks for reporting the issue! Could be caused by the latest update to Angular 4.0.0-rc.2. Will take a look at it as soon as I find some time.
