### ISSUE TITLE
npm start failure - rxjs problem

### ISSUE THREAD

**Issue by laurencefass** [mgechev/angular-seed#1893]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

npm install appears to work ok, but npm start fails.

```
root@7b829e626c27:/test/seed# npm start

> angular-seed@0.0.0 start /test/seed
> gulp serve.dev --color

[16:10:28] Requiring external module ts-node/register
[16:10:43] Loading tasks folder /test/seed/tools/tasks/seed
[16:10:43] Registering task /test/seed/tools/tasks/seed/build.assets.dev
[16:10:43] Registering task /test/seed/tools/tasks/seed/build.assets.prod
[16:10:43] Registering task /test/seed/tools/tasks/seed/build.bundle.rxjs
[16:10:43] Registering task /test/seed/tools/tasks/seed/build.bundles.app.aot
[16:10:43] Registering task /test/seed/tools/tasks/seed/build.bundles.app.rollup.aot
[16:10:43] Registering task /test/seed/tools/tasks/seed/build.bundles.app
[16:10:43] Registering task /test/seed/tools/tasks/seed/build.bundles
[16:10:43] Registering task /test/seed/tools/tasks/seed/build.docs
[16:10:43] Registering task /test/seed/tools/tasks/seed/build.html_css
[16:10:43] Registering task /test/seed/tools/tasks/seed/build.index.dev
[16:10:43] Registering task /test/seed/tools/tasks/seed/build.index.prod
[16:10:43] Registering task /test/seed/tools/tasks/seed/build.js.dev
[16:10:43] Registering task /test/seed/tools/tasks/seed/build.js.e2e
[16:10:43] Registering task /test/seed/tools/tasks/seed/build.js.prod.aot
[16:10:43] Registering task /test/seed/tools/tasks/seed/build.js.prod.rollup.aot
[16:10:43] Registering task /test/seed/tools/tasks/seed/build.js.prod
[16:10:43] Registering task /test/seed/tools/tasks/seed/build.js.test
[16:10:43] Registering task /test/seed/tools/tasks/seed/build.tools
[16:10:43] Registering task /test/seed/tools/tasks/seed/check.tools
[16:10:43] Registering task /test/seed/tools/tasks/seed/check.versions
[16:10:43] Registering task /test/seed/tools/tasks/seed/clean.all
[16:10:43] Registering task /test/seed/tools/tasks/seed/clean.coverage
[16:10:43] Registering task /test/seed/tools/tasks/seed/clean.dev
[16:10:43] Registering task /test/seed/tools/tasks/seed/clean.e2e
[16:10:43] Registering task /test/seed/tools/tasks/seed/clean.prod
[16:10:43] Registering task /test/seed/tools/tasks/seed/clean.tools
[16:10:43] Registering task /test/seed/tools/tasks/seed/clear.files
[16:10:43] Registering task /test/seed/tools/tasks/seed/compile.ahead.prod
[16:10:43] Registering task /test/seed/tools/tasks/seed/copy.prod.rollup.aot
[16:10:43] Registering task /test/seed/tools/tasks/seed/copy.prod
[16:10:43] Registering task /test/seed/tools/tasks/seed/e2e
[16:10:43] Registering task /test/seed/tools/tasks/seed/generate.manifest
[16:10:43] Registering task /test/seed/tools/tasks/seed/karma.run
[16:10:43] Registering task /test/seed/tools/tasks/seed/karma.run.with_coverage
[16:10:43] Registering task /test/seed/tools/tasks/seed/karma.watch
[16:10:43] Registering task /test/seed/tools/tasks/seed/minify.bundles
[16:10:43] Registering task /test/seed/tools/tasks/seed/noop
[16:10:43] Registering task /test/seed/tools/tasks/seed/print.banner
[16:10:43] Registering task /test/seed/tools/tasks/seed/serve.coverage
[16:10:43] Registering task /test/seed/tools/tasks/seed/serve.coverage.watch
[16:10:43] Registering task /test/seed/tools/tasks/seed/serve.docs
[16:10:43] Registering task /test/seed/tools/tasks/seed/server.prod
[16:10:43] Registering task /test/seed/tools/tasks/seed/server.start
[16:10:43] Registering task /test/seed/tools/tasks/seed/start.deving
[16:10:43] Registering task /test/seed/tools/tasks/seed/sw.manifest.static
[16:10:43] Registering task /test/seed/tools/tasks/seed/transpile.bundles.rollup.aot
[16:10:43] Registering task /test/seed/tools/tasks/seed/tslint
[16:10:43] Registering task /test/seed/tools/tasks/seed/watch.dev
[16:10:43] Registering task /test/seed/tools/tasks/seed/watch.e2e
[16:10:43] Registering task /test/seed/tools/tasks/seed/watch.test
[16:10:43] Registering task /test/seed/tools/tasks/seed/webdriver
[16:10:43] Loading tasks folder /test/seed/tools/tasks/project
[16:10:43] Registering task /test/seed/tools/tasks/project/sample.task
[16:10:43] Using gulpfile /test/seed/gulpfile.ts
[16:10:43] Starting 'serve.dev'...
[16:10:43] Starting 'build.dev'...
[16:10:43] Starting 'initialize'...
[16:10:43] Starting 'noop'...
[16:10:43] Finished 'noop' after 216 ms
[16:10:43] Finished 'initialize' after 221 ms
[16:10:43] Starting 'clean.once'...
[16:10:43] Starting 'check.tools'...
[16:10:44] Tools not compiled, skipping rebuild
[16:10:44] Finished 'check.tools' after 469 ms
[16:10:44] Starting 'clean.dev'...
[16:10:44] Deleted dist/dev
[16:10:44] Finished 'clean.dev' after 99 ms
[16:10:44] Starting 'clean.coverage'...
[16:10:44] Deleted coverage_js
[16:10:44] Deleted coverage
[16:10:44] Finished 'clean.coverage' after 120 ms
[16:10:44] Finished 'clean.once' after 695 ms
[16:10:44] Starting 'build.assets.dev'...
[16:10:44] Finished 'build.assets.dev' after 418 ms
[16:10:44] Starting 'build.html_css'...
[16:10:51] 'build.html_css' errored after 6.09 s
[16:10:51] Error: Cannot find module '.tmp/Rx.min.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.resolve (internal/module.js:27:19)
    at /test/seed/tools/config/seed.config.ts:675:59
    at Array.forEach (native)
    at normalizeDependencies (/test/seed/tools/config/seed.config.ts:675:6)
    at ProjectConfig.get [as DEPENDENCIES] (/test/seed/tools/config/seed.config.ts:355:12)
    at getExternalCss (/test/seed/tools/tasks/seed/build.html_css.ts:139:16)
    at getExternalCssStream (/test/seed/tools/tasks/seed/build.html_css.ts:131:19)
    at processExternalCss (/test/seed/tools/tasks/seed/build.html_css.ts:163:10)
    at processExternalStylesheets (/test/seed/tools/tasks/seed/build.html_css.ts:112:65)
[16:10:51] 'serve.dev' errored after 7.47 s
[16:10:51] Error in plugin 'run-sequence(build.html_css)'
Message:
    Cannot find module '.tmp/Rx.min.js'
Details:
    code: MODULE_NOT_FOUND
Stack:
Error: Cannot find module '.tmp/Rx.min.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.resolve (internal/module.js:27:19)
    at /test/seed/tools/config/seed.config.ts:675:59
    at Array.forEach (native)
    at normalizeDependencies (/test/seed/tools/config/seed.config.ts:675:6)
    at ProjectConfig.get [as DEPENDENCIES] (/test/seed/tools/config/seed.config.ts:355:12)
    at getExternalCss (/test/seed/tools/tasks/seed/build.html_css.ts:139:16)
    at getExternalCssStream (/test/seed/tools/tasks/seed/build.html_css.ts:131:19)
    at processExternalCss (/test/seed/tools/tasks/seed/build.html_css.ts:163:10)
    at processExternalStylesheets (/test/seed/tools/tasks/seed/build.html_css.ts:112:65)
[16:10:51] 'build.dev' errored after 7.47 s
[16:10:51] Error in plugin 'run-sequence(serve.dev)'
Message:
    Cannot find module '.tmp/Rx.min.js'
Details:
    code: MODULE_NOT_FOUND
Stack:
Error: Cannot find module '.tmp/Rx.min.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.resolve (internal/module.js:27:19)
    at /test/seed/tools/config/seed.config.ts:675:59
    at Array.forEach (native)
    at normalizeDependencies (/test/seed/tools/config/seed.config.ts:675:6)
    at ProjectConfig.get [as DEPENDENCIES] (/test/seed/tools/config/seed.config.ts:355:12)
    at getExternalCss (/test/seed/tools/tasks/seed/build.html_css.ts:139:16)
    at getExternalCssStream (/test/seed/tools/tasks/seed/build.html_css.ts:131:19)
    at processExternalCss (/test/seed/tools/tasks/seed/build.html_css.ts:163:10)
    at processExternalStylesheets (/test/seed/tools/tasks/seed/build.html_css.ts:112:65)
[16:10:51] 'build.dev' errored after 7.48 s
[16:10:51] Error in plugin 'run-sequence(build.html_css)'
Message:
    Cannot find module '.tmp/Rx.min.js'
Details:
    code: MODULE_NOT_FOUND
Stack:
Error: Cannot find module '.tmp/Rx.min.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.resolve (internal/module.js:27:19)
    at /test/seed/tools/config/seed.config.ts:675:59
    at Array.forEach (native)
    at normalizeDependencies (/test/seed/tools/config/seed.config.ts:675:6)
    at ProjectConfig.get [as DEPENDENCIES] (/test/seed/tools/config/seed.config.ts:355:12)
    at getExternalCss (/test/seed/tools/tasks/seed/build.html_css.ts:139:16)
    at getExternalCssStream (/test/seed/tools/tasks/seed/build.html_css.ts:131:19)
    at processExternalCss (/test/seed/tools/tasks/seed/build.html_css.ts:163:10)
    at processExternalStylesheets (/test/seed/tools/tasks/seed/build.html_css.ts:112:65)

npm ERR! Linux 4.4.57-boot2docker
npm ERR! argv "/root/.nvm/versions/node/v7.8.0/bin/node" "/root/.nvm/versions/node/v7.8.0/bin/npm" "start"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-seed@0.0.0 start: `gulp serve.dev --color`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-seed@0.0.0 start script 'gulp serve.dev --color'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp serve.dev --color
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2017-04-05T16_10_51_394Z-debug.log
root@7b829e626c27:/test/seed#
```

**Expected behavior**
npm start should start the application.

**Minimal reproduction of the problem with instructions**
npm start

**Please tell us about your environment:**
running npm in an unmounted folder ubuntu 14 docker container. there are existing problems running npm from a mounted folder but this is out of scope for this test.

* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` =
7.8

npm version
4.2

**Comment by Karasuni** [comment]
Did you manually add RxJS to the project? `.tmp/Rx.min.js` doesn't seem like the correct reference. Since it's supplied through `node_modules` you should be able to `import 'rxjs/Rx';` or `import { Observable } from 'rxjs/Observable';`.

**Comment by laurencefass** [comment]
i didnt change anything just ran npm start. im assuming RXJS is part of the install because its angular depends on it... my issue is that its not working out of the box but im happy to try any suggestion to "just make it work".

do you want to see a folder/file tree of any part of the install?

**Comment by Karasuni** [comment]
Check where you are referring to `.tmp/Rx.min.js`. AFAIK there is no `.tmp` directory. Did you run `npm install`?

**Comment by laurencefass** [comment]
yes npm install ran with no errors. i havent created a .tmp folder. should i?

**Comment by mgechev** [comment]
Looks like environment specific problem. I'll close the issue here and the discussion can be moved to gitter.

**Comment by Simonnnn** [comment]
yea thats cool that you moved this discussion to gitter, so people include me know the solution for this issue.
