### ISSUE TITLE
test.watch is running tests twice

### ISSUE THREAD

**Issue by Karasuni** [mgechev/angular-seed#1894]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
The karma watcher will build the code on file change and evaluate the tests twice: once with the old code and once with the new version of the code. The following is the resulting log after a single change in a single .spec.ts file was detected.
```
[13:41:54] Starting 'build.test'...
[13:41:54] Starting 'initialize'...
[13:41:54] Starting 'noop'...
[13:41:54] Finished 'noop' after 129 μs
[13:41:54] Finished 'initialize' after 555 μs
[13:41:54] Starting 'clean.once'...
[13:41:54] Skipping clean on rebuild
[13:41:54] Finished 'clean.once' after 194 μs
[13:41:54] Starting 'build.assets.dev'...
[13:41:54] Finished 'build.assets.dev' after 240 μs
[13:41:54] Starting 'build.html_css'...
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/css/indigo-pink.css".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/css/indigo-pink.css".
[13:41:54] Finished 'build.html_css' after 484 ms
[13:41:54] Starting 'build.js.dev'...

================================================================================

START:
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/common-cache/cache.model.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/about/about-routing.module.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/home/home-routing.module.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/d2t-api/d2t-api.config.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/shared/shared.module.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/d2t-api/feedback/feedback.model.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/login/login-routing.module.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/d2t-api/user/index.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/d2t-api/token/accesstoken.model.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/shared/authentication/authentication.service.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/shared/config/env.config.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/shared/name-list/index.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/shared/navbar/navbar.component.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/shared/toolbar/toolbar.component.js".
INFO [karma]: Delaying execution, these browsers are not ready: Chrome 57.0.2987 (Windows 7 0.0.0)
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/app-routing.module.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/app.component.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/system-config.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/app.module.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/i18n.providers.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/main.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/operators.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/about/about.component.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/about/about.module.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/common-cache/common-cache.module.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/common-cache/generic.storage.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/common-cache/local.storage.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/common-cache/memory.storage.impl.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/common-cache/memory.storage.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/common-cache/session.storage.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/home/home.component.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/home/home.module.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/d2t-api/d2t-api.module.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/d2t-api/feedback/feedback.service.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/login/login.module.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/login/login.component.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/d2t-api/feedback/index.js".
INFO [karma]: Delaying execution, these browsers are not ready: Chrome 57.0.2987 (Windows 7 0.0.0)
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/d2t-api/token/index.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/d2t-api/token/accesstokenrequest.model.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/d2t-api/token/token.service.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/d2t-api/user/user.model.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/d2t-api/user/user.service.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/shared/name-list/name-list.service.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/app-routing.module.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/app.component.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/app.module.js".
INFO [karma]: Delaying execution, these browsers are not ready: Chrome 57.0.2987 (Windows 7 0.0.0)
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/i18n.providers.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/main.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/operators.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/system-config.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/about/about-routing.module.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/about/about.component.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/about/about.module.js".
INFO [karma]: Delaying execution, these browsers are not ready: Chrome 57.0.2987 (Windows 7 0.0.0)
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/home/home-routing.module.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/home/home.component.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/home/home.module.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/common-cache/cache.model.js".
INFO [karma]: Delaying execution, these browsers are not ready: Chrome 57.0.2987 (Windows 7 0.0.0)
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/common-cache/common-cache.module.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/common-cache/common-cache.module.js".
INFO [karma]: Delaying execution, these browsers are not ready: Chrome 57.0.2987 (Windows 7 0.0.0)
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/common-cache/generic.storage.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/common-cache/local.storage.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/common-cache/memory.storage.impl.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/common-cache/memory.storage.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/common-cache/session.storage.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/d2t-api/d2t-api.config.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/d2t-api/d2t-api.module.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/login/login-routing.module.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/login/login.component.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/login/login.module.js".
INFO [karma]: Delaying execution, these browsers are not ready: Chrome 57.0.2987 (Windows 7 0.0.0)
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/shared/shared.module.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/d2t-api/feedback/feedback.model.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/d2t-api/feedback/feedback.service.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/d2t-api/feedback/index.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/d2t-api/token/accesstoken.model.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/d2t-api/token/accesstokenrequest.model.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/d2t-api/token/index.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/d2t-api/token/token.service.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/d2t-api/user/index.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/d2t-api/user/user.model.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/d2t-api/user/user.service.js".
INFO [karma]: Delaying execution, these browsers are not ready: Chrome 57.0.2987 (Windows 7 0.0.0)
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/shared/authentication/authentication.service.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/shared/config/env.config.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/shared/name-list/index.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/shared/name-list/name-list.service.js".
INFO [karma]: Delaying execution, these browsers are not ready: Chrome 57.0.2987 (Windows 7 0.0.0)
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/shared/navbar/navbar.component.js".
[13:42:06] Finished 'build.js.dev' after 12 s
[13:42:06] Starting 'build.js.test'...
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/shared/toolbar/toolbar.component.js".
INFO [karma]: Delaying execution, these browsers are not ready: Chrome 57.0.2987 (Windows 7 0.0.0)
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/index.html".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/app.component.spec.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/about/about.component.spec.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/common-cache/memory.storage.spec.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/login/login.component.spec.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/home/home.component.spec.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/shared/name-list/name-list.service.spec.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/d2t-api/feedback/feedback.service.spec.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/app.component.spec.js".
INFO [karma]: Delaying execution, these browsers are not ready: Chrome 57.0.2987 (Windows 7 0.0.0)
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/about/about.component.spec.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/common-cache/memory.storage.spec.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/home/home.component.spec.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/login/login.component.spec.js".
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/d2t-api/feedback/feedback.service.spec.js".
[13:42:12] Finished 'build.js.test' after 5.6 s
[13:42:12] Starting 'build.index.dev'...
INFO [karma]: Delaying execution, these browsers are not ready: Chrome 57.0.2987 (Windows 7 0.0.0)
INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/app/shared/name-list/name-list.service.spec.js".
[13:42:12] gulp-inject 3 files into index.html.
[13:42:12] gulp-inject 3 files into index.html.
[13:42:12] gulp-inject 2 files into index.html.
[13:42:12] Finished 'build.index.dev' after 116 ms
[13:42:12] Starting 'sw.manifest.static'...
0INFO [watcher]: Changed file "C:/DATA/PROJECTS/D2T/Frontend/dist/dev/index.html".
0INFO [karma]: Delaying execution, these browsers are not ready: Chrome 57.0.2987 (Windows 7 0.0.0)
[13:42:13] Finished 'sw.manifest.static' after 367 ms
[13:42:13] Finished 'build.test' after 19 s
  About component
    √ should work
  Feedback Service
    √ should return an Observable when getAllFeedback is called
    √ should resolve to list of feedback when getAllFeedback is called
  NameList Service
    √ should return an Observable when get called
    √ should resolve to list of names when get called
WARN: 'Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("[WARNING ->]<template><div class="mat-autocomplete-panel" role="listbox" [id]="id" [ngClass]="_getClassList()" #p"): ng:///MdAutocompleteModule/MdAutocomplete.html@0:0'
WARN: 'Could not find HammerJS. Certain Angular Material components may not work correctly.'
  Login component
    √ should work
INFO: 'GETTING', 'key'
LOG: 'found %s : %s', 'key', 'data'
  Memory Storage
    √ should store and retrieve a value
    √ should be true
    √ should also be true
LOG: 'result:', undefined
  Home component
    √ should work
WARN: 'Could not find HammerJS. Certain Angular Material components may not work correctly.'
LOG: 'Environment config', Object{API: 'http://localhost:8080/api/v1', ENV: 'DEV'}
  App component
    √ should build without a problem

================================================================================

START:

Finished in 0 secs / 0 secs @ 13:42:16 GMT+0200 (Romance Daylight Time)

SUMMARY:
√ 11 tests completed
  Feedback Service
    √ should return an Observable when getAllFeedback is called
    √ should resolve to list of feedback when getAllFeedback is called
  NameList Service
    √ should return an Observable when get called
    √ should resolve to list of names when get called
  About component
    √ should work
WARN: 'Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("[WARNING ->]<template><div class="mat-autocomplete-panel" role="listbox" [id]="id" [ngClass]="_getClassList()" #p"): ng:///MdAutocompleteModule/MdAutocomplete.html@0:0'
WARN: 'Could not find HammerJS. Certain Angular Material components may not work correctly.'
  Login component
    √ should work
INFO: 'GETTING', 'key'
LOG: 'found %s : %s', 'key', 'data'
  Memory Storage
    √ should store and retrieve a value
    √ should be true
    × should fail
LOG: 'result:', undefined
  Home component
    √ should work
WARN: 'Could not find HammerJS. Certain Angular Material components may not work correctly.'
LOG: 'Environment config', Object{API: 'http://localhost:8080/api/v1', ENV: 'DEV'}
  App component
    √ should build without a problem

Finished in 1.474 secs / 1.472 secs @ 13:42:19 GMT+0200 (Romance Daylight Time)

SUMMARY:
√ 10 tests completed
× 1 test failed

FAILED TESTS:
  Memory Storage
    × should fail
      Chrome 57.0.2987 (Windows 7 0.0.0)
    Expected true to equal false.
        at Object.eval (dist/dev/app/common-cache/memory.storage.spec.js:25:26) [ProxyZone]
        at ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:79:39) [ProxyZone]
        at Zone.run (node_modules/zone.js/dist/zone.js:125:43) [<root> => ProxyZone]
        at Object.<anonymous> (node_modules/zone.js/dist/jasmine-patch.js:104:34) [<root>]
        at ZoneQueueRunner.jasmine.QueueRunner.ZoneQueueRunner.execute (node_modules/zone.js/dist/jasmine-patch.js:132:42) [<root>]
        at Zone.runTask (node_modules/zone.js/dist/zone.js:165:47) [<root> => <root>]
        at drainMicroTaskQueue (node_modules/zone.js/dist/zone.js:593:35) [<root>]
        at ZoneTask.invoke (node_modules/zone.js/dist/zone.js:464:25) [<root>]
        at timer (node_modules/zone.js/dist/zone.js:1540:29) [<root>]
```

**Expected behavior**
I expect karma to run only the newest version of the code. Side note I would also expect the watcher to detect only the change in a single file and not all of them.

**Minimal reproduction of the problem with instructions**

1. Grab angular-seed and install the packages
2. Run test.watch
3. Change a .spec.ts file to change the test result

You will now see two test results: one result is for the old version of the file one is for the changed file.

**Please tell us about your environment:**
Running tests in IntelliJ IDEA (command line)

* **Angular Seed Version:** `23b051`

* **Node:** `node --version` = v7.1.0

**Comment by maxmarkus** [comment]
Hello, 
Am currently trying to debug this one. As far as I have seen, we (similar to many other projects using gulp and karma together) have a race condition issue. Karma's autowatch is being triggered immediately after the first files are updated (system-config.js in this seed's case). 

I see two approaches to fix this issue:

1.  Quick win, but poor performance: 
Adding _index.html_ explicitly to the includes and watch it, all other files `watched: false` and relevant files `nochache: true`. 
```
    // karma.conf.js
    { pattern: 'dist/dev/**/*.js', included: false, watched: false, served: true, nocache: true },
    { pattern: 'dist/dev/**/*.html', included: false, watched: false, served: true, nocache: true },
    { pattern: 'dist/dev/**/*.css', included: false, watched: false, served: true, nocache: true },
    { pattern: 'dist/dev/app/system-config.js', watched: false, included: true, served: true },
    // watching this only because it is the last in the processing chain and used to trigger karma watch
    { pattern: 'dist/dev/index.html', watched: true, included: false, served: true },
```
This triggers watch only once, but causes lot of i/o which slows down performance.

2. Suggested approach: 
Set karma to `autowatch: false` and programmatically hooking to `watch()` and triggering karma.runner.run manually this way as soon as _index.html_ has been found to be updated.

I am currently working on 2nd approach, but am happy about any input!

Best, Markus

**Comment by mgechev** [comment]
@maxmarkus we know when all the changes are happening and we can easily hook a `watch()` call.

This approach sounds good to me. In case you have time, would you want to open a PR and push your fix upstream?

**Comment by maxmarkus** [comment]
Unfortunately I couldn't get typing/executing issues with the runner fixed. Spent a day on it, but need to go on.

**Comment by maxmarkus** [comment]
I had a look at it again and found that `npm run start.deving` does not shows the issue, since it relies on its own watching mechanism combined with runSequence to build and running the tests. 
`npm run test.watch` on the other hand relies on gulp watch combined with karma's watcher, which leads to that race condition. So test.watch would work if being refactored to work similar like start.deving.
