### ISSUE TITLE
npm start fails "Cannot find module 'vinyl'

### ISSUE THREAD

**Issue by aleixpellicer** [mgechev/angular-seed#1896]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
after npm start:

```
Message:
    Cannot find module 'vinyl'
Details:
    code: MODULE_NOT_FOUND
Stack:
Error: Cannot find module 'vinyl'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\UniServerZ\www\Laukatu\HappyFeed\src\build\gulp.ts:4:15)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

**Expected behavior**
That npm start procedure works without failing

**Minimal reproduction of the problem with instructions**
npm install
npm start

**Please tell us about your environment:**
Windows, node 4.2.2, npm 2.14.7

**FIX**
add at the **end** of devDepenencies in package.json the following line:
``"vinyl": "^2.0.1"``

**Comment by mgechev** [comment]
Would you open a PR?
