### ISSUE TITLE
Error while build the seed to PROD

### ISSUE THREAD

**Issue by iodem** [mgechev/angular-seed#1907]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

I am trying to build the seed for the first tim (without any modifications) to test it. I succeed to build it with the command npm run build.dev. But when I try to use the command npm run build.prod, it failed with the following trace:

```
[10:10:48] Finished 'clean.prod' after 56 ms
[10:10:48] Starting 'tslint'...
TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1146:7)
    at Object.getRelativePath (/Users/XX/AngularProjects/node_modules/tslint/lib/configuration.js:248:17)
    at Linter.getResult (/Users/XX/AngularProjects/node_modules/tslint/lib/linter.js:120:31)
    at /Users/XX/AngularProjects/node_modules/gulp-tslint/index.js:103:30
    at wrappedMapper (/Users/XX/AngularProjects/node_modules/map-stream/index.js:84:19)
    at Stream.stream.write (/Users/XX/AngularProjects/node_modules/map-stream/index.js:96:21)
    at write (/Users/XX/AngularProjects/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/XX/AngularProjects/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/XX/AngularProjects/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:664:5)
```

**Expected behavior**

The build prod succeed
**Minimal reproduction of the problem with instructions**

Step 1: clone the repo
Step 2: execute the npm install
Step 3: run the command npm run build.dev (result succeed for this one)
Step 4: run the command npm run build.prod => build failed with the above description
 
**What is the motivation / use case for changing the behavior?**

Use the seed to prod env

**Please tell us about your environment:**

I am using OSX Darwin 16.5.0 with Visual Code and Chrome 

* **Angular Seed Version:** `a26407968cf5b7270e75b6bdfec46bdbe415fa09`

* **Node:** `node --version` =
node version: 6.10.2
npm version: 3.10.10

Thank you for your help.

**Comment by iodem** [comment]
Well, to succeed the build, I have commented the rules in the seed.tslint.json. I added instead:
`"extends": [
    "tslint:recommended"
  ],`
and it works.
Not sure if it is the right way or just a workaround.

**Comment by lakshmikant4u** [comment]
@iodem Did you simply run it by just adding "extends": [ "tslint:recommended" ] after commenting rules or tried to install some specific typescript versions, any other updation of node modules, typings etc etc?
With target as es5 in tsconfig.json.? For me nothing is working so.!

**Comment by mgechev** [comment]
I wasn't able to reproduce the issue but I believe the problem comes from `gulp-tslint`. Let me know if upgrade to 8.0.0 solves the problem.

**Comment by iodem** [comment]
@mgechev Yes you're right the update of gulp-tslint solve the issue. Thank you.
