### ISSUE TITLE
when tried to run npm test: "Path must be a string. Received null" 

### ISSUE THREAD

**Issue by vijaygawade18** [mgechev/angular-seed#1909]
[13:25:14] Starting 'test'...
[13:25:14] Starting 'tslint'...
TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:184:7)
    at Object.getRelativePath (E:\Tyco\project\New folder\TYC023\angular-master\node_modules\tslint\
lib\configuration.js:248:17)
    at Linter.getResult (E:\Tyco\project\New folder\TYC023\angular-master\node_modules\tslint\lib\li
nter.js:120:31)
    at E:\Tyco\project\New folder\TYC023\angular-master\node_modules\gulp-tslint\index.js:103:30
    at wrappedMapper (E:\Tyco\project\New folder\TYC023\angular-master\node_modules\map-stream\index
.js:84:19)
    at Stream.stream.write (E:\Tyco\project\New folder\TYC023\angular-master\node_modules\map-stream
\index.js:96:21)
    at write (E:\Tyco\project\New folder\TYC023\angular-master\node_modules\vinyl-fs\node_modules\re
adable-stream\lib\_stream_readable.js:623:24)
    at flow (E:\Tyco\project\New folder\TYC023\angular-master\node_modules\vinyl-fs\node_modules\rea
dable-stream\lib\_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (E:\Tyco\project\New folder\TYC023\angular-master\node_mo
dules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:664:5)
npm ERR! Test failed.  See above for more details.

**Comment by vijaygawade18** [comment]
I am not able to resolve this issue. Can you please help me with this.
Folder structure is:

── src                        <- source code of the application
│   └── client
│       ├── app
│       │   ├── containers 
│       │   │   ├── about
│       │   │   │  │
│       │   │   │  │── about.component.html
│       │   │   │  ├── about.component.spec.ts
│       │   │   │  ├── about.component.ts
│       │   │   │  ├── about.module.ts
│       │   │   │  ├── about.routes.ts
│       │   │   │  └── index.ts
│       │   ├── features
│       │   ├── shared
│       │   ├── app.component.e2e-spec.ts
│       │   ├── app.component.html
│       │   ├── app.component.spec.ts
│       │   ├── app.component.ts
│       │   ├── app.module.ts
│       │   ├── app.routes.ts

**Comment by mgechev** [comment]
Here's solution https://github.com/mgechev/angular-seed/issues/1907.

**Comment by vijaygawade18** [comment]
@mgechev thanks for the solution.

We tried your solution that solved tslint issue but now we  are getting other issue , please see the error below-

-----------------------------------------------------------
[09:45:36] 'sw.manifest.static' errored after 145 ms
[09:45:36] TSError: ? Unable to compile TypeScript
tools\tasks\seed\sw.manifest.static.ts (2,36): Cannot find module '@angular/service-worker/build/gul
p'. (2307)
    at getOutput (E:\Tyco\project\latest\TYC023\angular-master\node_modules\ts-node\src\index.ts:308
:17)
    at E:\Tyco\project\latest\TYC023\angular-master\node_modules\ts-node\src\index.ts:334:18
    at Object.compile (E:\Tyco\project\latest\TYC023\angular-master\node_modules\ts-node\src\index.t
s:462:19)
    at Module.m._compile (E:\Tyco\project\latest\TYC023\angular-master\node_modules\ts-node\src\inde
x.ts:392:44)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .ts] (E:\Tyco\project\latest\TYC023\angula
r-master\node_modules\ts-node\src\index.ts:395:12)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
[09:45:36] 'serve.dev' errored after 7.67 s
[09:45:36] TSError in plugin 'run-sequence(sw.manifest.static)'
Message:
    ? Unable to compile TypeScript
------------------------------------------------

Your help on this would be appreciated as we are facing this issue since start, Initially we got this issue when we added lazy loading but after removing it was fine. Now again we are getting this issue. 

Would be thank full for your kind help !!

Regards
Vijay
