### ISSUE TITLE
fail to build the files for production after added new module, it is happen when run "npm run build.prod.rollup.aot"

### ISSUE THREAD

**Issue by kmkmathan** [mgechev/angular-seed#1913]
**Current behavior**
I added path of ng2-progressbar module in SYSTEM_CONFIG_DEV (config/seed.config.ts) 
when i run "npm start" it is working fine.but when i m using npm run build.prod.rollup.aot, It shows below error.
How to I fix this.
`{ Error: 'NgProgressModule' is not exported by node_modules\ng2-progressbar.js
    at error (E:\angular-seed-hep\node_modules\rollup\src\utils\error.js:2:14)
    at Module.error$1 [as error] (E:\angular-seed-hep\node_modules\rollup\src\Module.js:303:2)
    at Module.trace (E:\angular-seed-hep\node_modules\rollup\src\Module.js:400:10)
    at ModuleScope.findDeclaration (E:\angular-seed-hep\node_modules\rollup\src\ast\scopes\ModuleScope.js:52:22)
    at Identifier.bind (E:\angular-seed-hep\node_modules\rollup\src\ast\nodes\Identifier.js:22:29)
    at E:\angular-seed-hep\node_modules\rollup\src\ast\Node.js:6:34
    at ArrayExpression.eachChild (E:\angular-seed-hep\node_modules\rollup\src\ast\Node.js:18:20)
    at ArrayExpression.bind (E:\angular-seed-hep\node_modules\rollup\src\ast\Node.js:6:8)
    at E:\angular-seed-hep\node_modules\rollup\src\ast\Node.js:6:34
    at Node.eachChild (E:\angular-seed-hep\node_modules\rollup\src\ast\Node.js:21:5)
  code: 'MISSING_EXPORT',
  url: 'https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module',
  pos: 1155,
  loc:
   { file: 'E:\\angular-seed-hep\\dist\\tmp\\app\\app.module.js',
     line: 18,
     column: 9 },
  frame: '16: import { SolutionModule } from \'./solution/solution.module\';\n17: import { SharedModule } from \'./shared/shared.module\';\n18: import { NgProgressModule } from \'ng2-progressbar\';\n             ^\n19: let AppModule = class AppModule {\n20: };' }
`

**Expected behavior**

**Please tell us about your environment:**
Window 7

* **Angular Seed Version:0.0.0* **

* **Node:** `node --version` =v6.10.1

**Comment by mgechev** [comment]
In case you have problems configuring rollup I'd recommend you to either review their documentation or switch to the CLI. Although Angular seed provides great flexibility and allows you to squeeze every byte out of your bundle, Angular CLI provides a good way to get started without understanding the required tooling in depth.
