### ISSUE TITLE
CSSTask breaking project when handing off project to someone else and running on their machine.

### ISSUE THREAD

**Issue by premiumwd** [mgechev/angular-seed#1967]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
Added scss files and enabled scss. Handed it off to someone else, and get the following error.

**Expected behavior**
Able to npm start without error.

**Minimal reproduction of the problem with instructions**
```
[14:36:50] TSError: ⨯ Unable to compile TypeScript
tools\tasks\css_task.ts (4,23): Class 'CssTask' incorrectly extends base class 'Task'.
  Types of property 'shallRun' are incompatible.
    Type '(files: String[]) => string | boolean' is not assignable to type '(files: string[]) => boolean'.
      Type 'string | boolean' is not assignable to type 'boolean'.
        Type 'string' is not assignable to type 'boolean'. (2415)
    at getOutput (D:\webroot\phenomenex v2\node_modules\ts-node\src\index.ts:300:15)
    at D:\webroot\phenomenex v2\node_modules\ts-node\src\index.ts:330:16
    at Object.compile (D:\webroot\phenomenex v2\node_modules\ts-node\src\index.ts:489:17)
    at Module.m._compile (D:\webroot\phenomenex v2\node_modules\ts-node\src\index.ts:382:43)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .ts] (D:\webroot\phenomenex v2\node_modules\ts-node\src\index.ts:385:12)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
[14:36:50] 'serve.dev' errored after 6.15 s
[14:36:50] TSError in plugin 'run-sequence(build.html_css)'
Message:
    ⨯ Unable to compile TypeScript
tools\tasks\css_task.ts (4,23): Class 'CssTask' incorrectly extends base class 'Task'.
  Types of property 'shallRun' are incompatible.
    Type '(files: String[]) => string | boolean' is not assignable to type '(files: string[]) => boolean'.
      Type 'string | boolean' is not assignable to type 'boolean'.
        Type 'string' is not assignable to type 'boolean'. (2415)
Details:
    diagnostics: [object Object]
Stack:
TSError: ⨯ Unable to compile TypeScript
tools\tasks\css_task.ts (4,23): Class 'CssTask' incorrectly extends base class 'Task'.
  Types of property 'shallRun' are incompatible.
    Type '(files: String[]) => string | boolean' is not assignable to type '(files: string[]) => boolean'.
      Type 'string | boolean' is not assignable to type 'boolean'.
        Type 'string' is not assignable to type 'boolean'. (2415)
    at getOutput (D:\webroot\phenomenex v2\node_modules\ts-node\src\index.ts:300:15)
    at D:\webroot\phenomenex v2\node_modules\ts-node\src\index.ts:330:16
    at Object.compile (D:\webroot\phenomenex v2\node_modules\ts-node\src\index.ts:489:17)
    at Module.m._compile (D:\webroot\phenomenex v2\node_modules\ts-node\src\index.ts:382:43)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .ts] (D:\webroot\phenomenex v2\node_modules\ts-node\src\index.ts:385:12)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
[14:36:50] 'build.dev' errored after 6.15 s
[14:36:50] TSError in plugin 'run-sequence(build.html_css)'
Message:
    ⨯ Unable to compile TypeScript
tools\tasks\css_task.ts (4,23): Class 'CssTask' incorrectly extends base class 'Task'.
  Types of property 'shallRun' are incompatible.
    Type '(files: String[]) => string | boolean' is not assignable to type '(files: string[]) => boolean'.
      Type 'string | boolean' is not assignable to type 'boolean'.
        Type 'string' is not assignable to type 'boolean'. (2415)
Details:
    diagnostics: [object Object]
Stack:
TSError: ⨯ Unable to compile TypeScript
tools\tasks\css_task.ts (4,23): Class 'CssTask' incorrectly extends base class 'Task'.
  Types of property 'shallRun' are incompatible.
    Type '(files: String[]) => string | boolean' is not assignable to type '(files: string[]) => boolean'.
      Type 'string | boolean' is not assignable to type 'boolean'.
        Type 'string' is not assignable to type 'boolean'. (2415)
    at getOutput (D:\webroot\phenomenex v2\node_modules\ts-node\src\index.ts:300:15)
    at D:\webroot\phenomenex v2\node_modules\ts-node\src\index.ts:330:16
    at Object.compile (D:\webroot\phenomenex v2\node_modules\ts-node\src\index.ts:489:17)
    at Module.m._compile (D:\webroot\phenomenex v2\node_modules\ts-node\src\index.ts:382:43)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .ts] (D:\webroot\phenomenex v2\node_modules\ts-node\src\index.ts:385:12)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-seed@1.0.0 start: `gulp serve.dev --color`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-seed@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hsadmin\AppData\Roaming\npm-cache\_logs\2017-06-09T21_36_50_733Z-debug.log
```

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.0.0
3 info using node@v8.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular-seed@1.0.0~prestart: angular-seed@1.0.0
6 silly lifecycle angular-seed@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle angular-seed@1.0.0~start: angular-seed@1.0.0
8 verbose lifecycle angular-seed@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle angular-seed@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\webroot\phenomenex v2\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;D:\webapp\php-5.3.8;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Program Files (x86)\Common Files\Intuit\QBPOSSDKRuntime;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files (x86)\Brackets\command;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;;D:\webapp\Microsoft VS Code\bin;C:\Users\hsadmin\AppData\Roaming\npm
10 verbose lifecycle angular-seed@1.0.0~start: CWD: D:\webroot\phenomenex v2
11 silly lifecycle angular-seed@1.0.0~start: Args: [ '/d /s /c', 'gulp serve.dev --color' ]
12 silly lifecycle angular-seed@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle angular-seed@1.0.0~start: Failed to exec start script
14 verbose stack Error: angular-seed@1.0.0 start: `gulp serve.dev --color`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at EventEmitter.emit (events.js:213:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at ChildProcess.emit (events.js:213:7)
14 verbose stack     at maybeClose (internal/child_process.js:887:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
15 verbose pkgid angular-seed@1.0.0
16 verbose cwd D:\webroot\phenomenex v2
17 verbose Windows_NT 6.1.7601
18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 verbose node v8.0.0
20 verbose npm  v5.0.0
21 error code ELIFECYCLE
22 error errno 1
23 error angular-seed@1.0.0 start: `gulp serve.dev --color`
23 error Exit status 1
24 error Failed at the angular-seed@1.0.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Please tell us about your environment:**

* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` =

**Comment by mgechev** [comment]
The CSSTask class doesn't extend properly the base abstract Task class. This doesn't seem like an issue in the seed.

**Comment by premiumwd** [comment]
@mgechev This is only an issue when i added scss to project, handing it off to someone else and having them npm start the project after they install it.

**Comment by jmjones88** [comment]
@mgechev @premiumwd It just happened to me too after a restart, and it's my project on my computer.. I'm guessing I should disable scss and give it a shot? Project was just working fine!

**Comment by jmjones88** [comment]
Ah @premiumwd mine was setting `ENABLE_SCSS=1;` instead of `ENABLE_SCSS=true;` in the config.. typescript was confused about the type of number vs boolean!

**Comment by premiumwd** [comment]
@jmjones88 doesn't matter either one. I decided to use angular cli, to many headaches, this guy has his plate full.
