### ISSUE TITLE
Unexpected token < in JSON at position 0, after import minio

### ISSUE THREAD

**Issue by oMinGWo** [mgechev/angular-seed#1976]
**Current behavior**
1.import minio just like the guaid in wiki
2.npm start to start my project

**Expected behavior**
expected to start my project successfully

* **Angular Seed Version:** `dont know`

* **Node:** `node --version` =6.10.0
systemjs version = 0.19.41

Here is the reuof my browser.
```

core.umd.js:3064 EXCEPTION: Uncaught (in promise): Error: Error in http://local.mooctest.net/app/common/login/login.component.html:54:32 caused by: Unexpected token < in JSON at position 0
Error: Error in http://local.mooctest.net/app/common/login/login.component.html:54:32 caused by: Unexpected token < in JSON at position 0
    at ViewWrappedError.ZoneAwareError (http://local.mooctest.net/node_modules/zone.js/dist/zone.js?1497531933731:992:33)
    at ViewWrappedError.BaseError [as constructor] (http://local.mooctest.net/node_modules/@angular/core/bundles/core.umd.js:1239:20)
    at ViewWrappedError.WrappedError [as constructor] (http://local.mooctest.net/node_modules/@angular/core/bundles/core.umd.js:1297:20)
    at new ViewWrappedError (http://local.mooctest.net/node_modules/@angular/core/bundles/core.umd.js:6167:20)
    at CompiledTemplate.proxyViewClass.DebugAppView._rethrowWithContext (http://local.mooctest.net/node_modules/@angular/core/bundles/core.umd.js:12385:27)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://local.mooctest.net/node_modules/@angular/core/bundles/core.umd.js:12358:22)
    at CompiledTemplate.proxyViewClass.AppView.internalDetectChanges (http://local.mooctest.net/node_modules/@angular/core/bundles/core.umd.js:12193:22)
    at CompiledTemplate.proxyViewClass.View_LoginComponent_Host0.detectChangesInternal (/MTCommonModule/LoginComponent/host.ngfactory.js:29:19)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://local.mooctest.net/node_modules/@angular/core/bundles/core.umd.js:12208:18)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://local.mooctest.net/node_modules/@angular/core/bundles/core.umd.js:12355:48)
    at ViewRef_.detectChanges (http://local.mooctest.net/node_modules/@angular/core/bundles/core.umd.js:9377:24)
    at RouterOutlet.activate (http://local.mooctest.net/node_modules/@angular/router/bundles/router.umd.js:5058:46)
    at ActivateRoutes.placeComponentIntoOutlet (http://local.mooctest.net/node_modules/@angular/router/bundles/router.umd.js:4337:20)
    at ActivateRoutes.activateRoutes (http://local.mooctest.net/node_modules/@angular/router/bundles/router.umd.js:4304:30)
    at eval (http://local.mooctest.net/node_modules/@angular/router/bundles/router.umd.js:4240:62)
```

is this the problem of systemjs's version?
my systemjs version is 0.19.41

**Comment by patrickmichalina** [comment]
It could be a few things, but probably is a SystemJS configuration issue. Double check your configuration.

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
