### ISSUE TITLE
Your current PostCSS version is 6.0.2, but postcss-minify-selectors uses 5.2.17. Perhaps this is the source of the error below.

### ISSUE THREAD

**Issue by saikiranmandhala** [mgechev/angular-seed#1978]
I am facing the below issue while running the `>npm run serve.prod`

`Your current PostCSS version is 6.0.2, but postcss-minify-selectors uses 5.2.17. Perhaps this is the source of the error below.

C:\Users\u500573\mgechev\node_modules\postcss-selector-parser\dist\processor.js:29
                throw new Error(e);
                      ^
Error: Unexpected "space" found.
    at new error (C:\Users\u500573\mgechev\node_modules\postcss-selector-parser\dist\processor.js:29:23)
    at Parser.error (C:\Users\u500573\mgechev\node_modules\postcss-selector-parser\dist\parser.js:234:15)
    at Parser.pseudo (C:\Users\u500573\mgechev\node_modules\postcss-selector-parser\dist\parser.js:362:18)
    at Parser.parse (C:\Users\u500573\mgechev\node_modules\postcss-selector-parser\dist\parser.js:551:22)
    at Parser.loop (C:\Users\u500573\mgechev\node_modules\postcss-selector-parser\dist\parser.js:519:18)
    at new Parser (C:\Users\u500573\mgechev\node_modules\postcss-selector-parser\dist\parser.js:104:21)
    at Processor.process (C:\Users\u500573\mgechev\node_modules\postcss-selector-parser\dist\processor.js:26:21)
    at getParsed (C:\Users\u500573\mgechev\node_modules\postcss-minify-selectors\dist\index.js:32:59)
    at optimise (C:\Users\u500573\mgechev\node_modules\postcss-minify-selectors\dist\index.js:139:21)
    at C:\Users\u500573\mgechev\node_modules\postcss\lib\container.es6:198:28`

Do I need to update the postcss-minify-selectors ?

**Comment by mgechev** [comment]
Angular seed doesn't depend on `postcss-minify-selectors`. If you get the error for the version mismatch probably that's the issue you should fix.

Let me know how it goes.

**Comment by saikiranmandhala** [comment]
Stringent timelines, For time being I have commented out the `pipe(plugins.postcss(processors)` and manually minified the CSS files. Will let you know when I come back to this issue. BTW the best  & great Anguar2 seed project available on the internet. Thanks
