### ISSUE TITLE
Cannot install Angular Seed, crashes after NPM START

### ISSUE THREAD

**Issue by ferile** [mgechev/angular-seed#2002]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**

I try to install Angular seed, using NPM INSTALL, and then run NPM START. After I run start, I get error messages and it bombs out without building. 

**Expected behavior**

NPM START would work. 

**Minimal reproduction of the problem with instructions**

I try to install Angular seed, using NPM INSTALL, and then run NPM START. After I run start, I get error messages and it bombs out without building. 

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 10 64x, Visual Studio Code, NPM, IIS

* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` = 6.10

'clean.once' errored after 264 μs
[08:16:06] Error: Task check.tools is not configured as a task on gulp.  If this is a submodule, you may need to use require('run-sequence').use(gulp).
    at C:\xampp\htdocs\MobileMeetings\ui\Admin Portal\node_modules\run-sequence\index.js:20:10
    at Array.forEach (native)
    at verifyTaskSets (C:\xampp\htdocs\MobileMeetings\ui\Admin Portal\node_modules\run-sequence\index.js:13:11)
    at runSequence (C:\xampp\htdocs\MobileMeetings\ui\Admin Portal\node_modules\run-sequence\index.js:92:2)
    at Gulp.<anonymous> (C:\xampp\htdocs\MobileMeetings\ui\Admin Portal\gulpfile.js:37:9)
    at module.exports (C:\xampp\htdocs\MobileMeetings\ui\Admin Portal\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\xampp\htdocs\MobileMeetings\ui\Admin Portal\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\xampp\htdocs\MobileMeetings\ui\Admin Portal\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\xampp\htdocs\MobileMeetings\ui\Admin Portal\node_modules\orchestrator\index.js:134:8)
    at runNextSet (C:\xampp\htdocs\MobileMeetings\ui\Admin Portal\node_modules\run-sequence\index.js:86:16)
[08:16:06] 'serve.dev' errored after 27 ms
[08:16:06] Error in plugin 'run-sequence(clean.once)'
Message:
    Task check.tools is not configured as a task on gulp.  If this is a submodule, you may need to use require('run-sequence').use(gulp).
Stack:
Error: Task check.tools is not configured as a task on gulp.  If this is a submodule, you may need to use require('run-sequence').use(gulp).
    at C:\xampp\htdocs\MobileMeetings\ui\Admin Portal\node_modules\run-sequence\index.js:20:10
    at Array.forEach (native)
    at verifyTaskSets (C:\xampp\htdocs\MobileMeetings\ui\Admin Portal\node_modules\run-sequence\index.js:13:11)
    at runSequence (C:\xampp\htdocs\MobileMeetings\ui\Admin Portal\node_modules\run-sequence\index.js:92:2)
    at Gulp.<anonymous> (C:\xampp\htdocs\MobileMeetings\ui\Admin Portal\gulpfile.js:37:9)
    at module.exports (C:\xampp\htdocs\MobileMeetings\ui\Admin Portal\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\xampp\htdocs\MobileMeetings\ui\Admin Portal\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\xampp\htdocs\MobileMeetings\ui\Admin Portal\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\xampp\htdocs\MobileMeetings\ui\Admin Portal\node_modules\orchestrator\index.js:134:8)
    at runNextSet (C:\xampp\htdocs\MobileMeetings\ui\Admin Portal\node_modules\run-sequence\index.js:86:16)
[08:16:06] 'build.dev' errored after 36 ms
[08:16:06] Error in plugin 'run-sequence(serve.dev)'
Message:
    Task check.tools is not configured as a task on gulp.  If this is a submodule, you may need to use require('run-sequence').use(gulp).
Stack:
Error: Task check.tools is not configured as a task on gulp.  If this is a submodule, you may need to use require('run-sequence').use(gulp).
    at C:\xampp\htdocs\MobileMeetings\ui\Admin Portal\node_modules\run-sequence\index.js:20:10
    at Array.forEach (native)
    at verifyTaskSets (C:\xampp\htdocs\MobileMeetings\ui\Admin Portal\node_modules\run-sequence\index.js:13:11)
    at runSequence (C:\xampp\htdocs\MobileMeetings\ui\Admin Portal\node_modules\run-sequence\index.js:92:2)
    at Gulp.<anonymous> (C:\xampp\htdocs\MobileMeetings\ui\Admin Portal\gulpfile.js:37:9)
    at module.exports (C:\xampp\htdocs\MobileMeetings\ui\Admin Portal\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\xampp\htdocs\MobileMeetings\ui\Admin Portal\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\xampp\htdocs\MobileMeetings\ui\Admin Portal\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\xampp\htdocs\MobileMeetings\ui\Admin Portal\node_modules\orchestrator\index.js:134:8)
    at runNextSet (C:\xampp\htdocs\MobileMeetings\ui\Admin Portal\node_modules\run-sequence\index.js:86:16)
[08:16:06] 'build.dev' errored after 52 ms
[08:16:06] Error in plugin 'run-sequence(clean.once)'
Message:
    Task check.tools is not configured as a task on gulp.  If this is a submodule, you may need to use require('run-sequence').use(gulp).
Stack:
Error: Task check.tools is not configured as a task on gulp.  If this is a submodule, you may need to use require('run-sequence').use(gulp).
    at C:\xampp\htdocs\MobileMeetings\ui\Admin Portal\node_modules\run-sequence\index.js:20:10
    at Array.forEach (native)
    at verifyTaskSets (C:\xampp\htdocs\MobileMeetings\ui\Admin Portal\node_modules\run-sequence\index.js:13:11)
    at runSequence (C:\xampp\htdocs\MobileMeetings\ui\Admin Portal\node_modules\run-sequence\index.js:92:2)
Task check.tools is not configured as a task on gulp.  If this is a submodule, you may need to use require('run-sequence').use(gulp).
Stack:
Error: Task check.tools is not configured as a task on gulp.  If this is a submodule, you may need to use require('run-sequence').use(gulp).
    at C:\xampp\htdocs\MobileMeetings\ui\Admin Portal\node_modules\run-sequence\index.js:20:10
    at Array.forEach (native)
    at verifyTaskSets (C:\xampp\htdocs\MobileMeetings\ui\Admin Portal\node_modules\run-sequence\index.js:13:11)
    at runSequence (C:\xampp\htdocs\MobileMeetings\ui\Admin Portal\node_modules\run-sequence\index.js:92:2)
    at Gulp.<anonymous> (C:\xampp\htdocs\MobileMeetings\ui\Admin Portal\gulpfile.js:37:9)
    at module.exports (C:\xampp\htdocs\MobileMeetings\ui\Admin Portal\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\xampp\htdocs\MobileMeetings\ui\Admin Portal\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\xampp\htdocs\MobileMeetings\ui\Admin Portal\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\xampp\htdocs\MobileMeetings\ui\Admin Portal\node_modules\orchestrator\index.js:134:8)
    at runNextSet (C:\xampp\htdocs\MobileMeetings\ui\Admin Portal\node_modules\run-sequence\index.js:86:16)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed@0.0.0 start: `gulp serve.dev --color`
npm ERR! Exit status 1

**Comment by mgechev** [comment]
@ferile probably you're using old version of the seed. Make sure you've updated to the latest code in master. There's no task `clean.once`.
