### ISSUE TITLE
getting typescript compilation error

### ISSUE THREAD

**Issue by ccommando** [mgechev/angular-seed#2008]
```
TSError: ⨯ Unable to compile TypeScript
Cannot find type definition file for 'node'. (2688)
gulpfile.ts (1,23): Cannot find module 'gulp'. (2307)
gulpfile.ts (2,23): Cannot find module 'gulp-util'. (2307)
gulpfile.ts (3,30): Cannot find module 'run-sequence'. (2307)
gulpfile.ts (5,20): Cannot find module './tools/config'. (2307)
gulpfile.ts (6,47): Cannot find module './tools/utils'. (2307)
    at getOutput (/var/www/aegonlife_ng2/node_modules/ts-node/src/index.ts:316:17)
    at /var/www/aegonlife_ng2/node_modules/ts-node/src/index.ts:347:18
    at Object.compile (/var/www/aegonlife_ng2/node_modules/ts-node/src/index.ts:474:19)
    at Module.m._compile (/var/www/aegonlife_ng2/node_modules/ts-node/src/index.ts:410:44)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/var/www/aegonlife_ng2/node_modules/ts-node/src/index.ts:413:12)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
```

**Comment by mgechev** [comment]
Please follow the issue template.

This error message doesn't provide any information for reproducing the problem.

**Comment by lbodor** [comment]
@ccommando, are you using typescript 2.4.1. See #2003.
