### ISSUE TITLE
build.js.prod.rollup.aot failing to resolveModule

### ISSUE THREAD

**Issue by paulussup** [mgechev/angular-seed#2011]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

Running rollup build cause following error with fresh clone.

```(stack)

[20:08:35] Starting 'build.js.prod.rollup.aot'...

/tmp/angular-seed/node_modules/typescript/lib/typescript.js:24817
                var resolvedFileName = result.resolvedModule && result.resolvedModule.resolvedFileName;
                                             ^
TypeError: Cannot read property 'resolvedModule' of undefined
    at Object.set (/tmp/angular-seed/node_modules/typescript/lib/typescript.js:24817:46)
    at Object.resolveModuleName (/tmp/angular-seed/node_modules/typescript/lib/typescript.js:24895:40)
    at loader_1 (/tmp/angular-seed/node_modules/typescript/lib/typescript.js:67002:78)
    at loadWithLocalCache (/tmp/angular-seed/node_modules/typescript/lib/typescript.js:66948:42)
    at resolveModuleNamesWorker (/tmp/angular-seed/node_modules/typescript/lib/typescript.js:67003:88)
    at resolveModuleNamesReusingOldState (/tmp/angular-seed/node_modules/typescript/lib/typescript.js:67174:24)
    at processImportedModules (/tmp/angular-seed/node_modules/typescript/lib/typescript.js:68027:35)
    at findSourceFile (/tmp/angular-seed/node_modules/typescript/lib/typescript.js:67937:17)
    at processSourceFile (/tmp/angular-seed/node_modules/typescript/lib/typescript.js:67840:27)
    at processRootFile (/tmp/angular-seed/node_modules/typescript/lib/typescript.js:67728:13)

```
**Expected behavior**

Should run rollup build.

**Minimal reproduction of the problem with instructions**

`npm install`
`npm run build.prod.rollup.aot`

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

MacOSx

* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` = 6.6

**Comment by Doehl** [comment]
It is an issue with the latest release of gulp-typescript. Downgrading to 3.1.7 fix the issue.

**Comment by Doehl** [comment]
[Related issue](https://github.com/ivogabe/gulp-typescript/issues/525)

**Comment by mgechev** [comment]
@Doehl thanks for pointing this out!

**Comment by mgechev** [comment]
https://github.com/mgechev/angular-seed/commit/a2db8ce6babc2f40792323f77f5e241398cce6a7
