### ISSUE TITLE
node-gyp error - npm install

### ISSUE THREAD

**Issue by skolli853780** [mgechev/angular-seed#2061]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
Got the latest angular seed and started npm install.. getting follow error

C:\Users\ssk3\Documents\GitHub\oar-sdp\node_modules\weak>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available tools versions are "14.0", "4.0".
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\ssk3\Documents\GitHub\oar-sdp\node_modules\weak
gyp ERR! node -v v6.11.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

**Expected behavior**

npm install should work fine without any errors

**Minimal reproduction of the problem with instructions**
Get the latest angular seed and run npm install

**What is the motivation / use case for changing the behavior?**

Upgrade to Angular 4.3

**Please tell us about your environment:**

Windows 10, WebStorm

* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` = 6.1

**Comment by skolli853780** [comment]
npm i utf-8-validate --msvs_version=2015 fixed the problem
