### ISSUE TITLE
Error when trying to integrate Angular/material

### ISSUE THREAD

**Issue by binhle410** [mgechev/angular-seed#2087]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

I added angular material  as the site instructs https://material.angular.io/guide/getting-started but then, I got this error
``(index):318 SyntaxError: Unexpected token <
    at eval (<anonymous>)
    at evaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1506310767982:2821:16)
    at http://localhost:5555/node_modules/systemjs/dist/system.src.js?1506310767982:3620:21
    at dynamicExecute (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1506310767982:1144:26)
    at doEvaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1506310767982:1091:13)
    at ensureEvaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1506310767982:999:13)
    at http://localhost:5555/node_modules/systemjs/dist/system.src.js?1506310767982:1017:20
    at Object.eval (http://localhost:5555/app/home/home.module.js:16:18)
    at eval (http://localhost:5555/app/home/home.module.js:38:4)
    at eval (http://localhost:5555/app/home/home.module.js:39:3) Not expecting this error? Report it at https://github.com/mgechev/angular-seed/issues
``
**Expected behavior**

The site should display without error in the console 
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 10, Visual Code, npm, 
* **Angular Seed Version:** `60b4f54`

* **Node:** `node --version` = 6.11.2

**Comment by nhutcorp** [comment]
Have you read this tutorial yet? https://github.com/mgechev/angular-seed/wiki/Integration-with-AngularMaterial2

**Comment by binhle410** [comment]
Sorry that I missed the documentation.

**Comment by andreslon** [comment]
I have the same problem, and the documentation not working, please help me.
