### ISSUE TITLE
Not able to run test for individual apps

### ISSUE THREAD

**Issue by skolli853780** [mgechev/angular-seed#2092]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

npm test does not take app parameter.. we have 2 applications using same angular seed.
if I run npm test -- --app sd, it does not run tests for sd application

**Expected behavior**

Like the way, we can start and build individual applications by passing --app parameter, npm test with app parameter should run 
**Minimal reproduction of the problem with instructions**

execute npm test -- --app <name of the app>

**What is the motivation / use case for changing the behavior?**

In a distributed team environment, developers should be able to run tests on individual application
**Please tell us about your environment:**

Windows 10

* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` =

**Comment by mgechev** [comment]
@skolli853780 thanks for opening this issue. Would love to get a PR for that!

**Comment by skolli853780** [comment]
Can you please assign this to one of the Angular seed contributors? I am not an expert in this area..

**Comment by aap21** [comment]
Hi

I am also attempting to run npm test and I get errors out of the box. Any suggestions on correctly executing a simple unit app component unit test?

Below are the errors:

27 06 2018 14:15:12.548:INFO [karma]: Karma v2.0.3 server started at http://0.0.0.0:9877/
27 06 2018 14:15:12.549:INFO [launcher]: Launching browser Chrome with unlimited concurrency
27 06 2018 14:15:12.557:INFO [launcher]: Starting browser Chrome
**27 06 2018 14:15:18.335:INFO [Chrome 67.0.3396 (Windows 10 0.0.0)]: Connected on socket jY7LkPPjEwsoh-e2AAAA with id 86362703
27 06 2018 14:15:21.752:WARN [web-server]: 404: /base/node_modules/@ng-idle/core/bundles/core.umd.js
27 06 2018 14:15:21.760:WARN [web-server]: 404: /base/node_modules/@ng-idle/keepalive/bundles/keepalive.umd.js**
Chrome 67.0.3396 (Windows 10 0.0.0) ERROR: 'Error: Fetch error: 404 Not Found
    at http://localhost:9877/base/node_modules/systemjs/dist/system.src.js?24c6d822129935a215cd79d5738b40d09661f3d5:1454:15
    at ZoneDelegate.invoke (http://localhost:9877/base/node_modules/zone.js/dist/zone.js?31405934ea8c08e72de05c03ca00a77319718226:388:26)
    at Zone.run (http://localhost:9877/base/node_modules/zone.js/dist/zone.js?31405934ea8c08e72de05c03ca00a77319718226:138:43)
    at http://localhost:9877/base/node_modules/zone.js/dist/zone.js?31405934ea8c08e72de05c03ca00a77319718226:872:34
    at ZoneDelegate.invokeTask (http://localhost:9877/base/node_modules/zone.js/dist/zone.js?31405934ea8c08e72de05c03ca00a77319718226:421:31)
    at Zone.runTask (http://localhost:9877/base/node_modules/zone.js/dist/zone.js?31405934ea8c08e72de05c03ca00a77319718226:188:47)
    at drainMicroTaskQueue (http://localhost:9877/base/node_modules/zone.js/dist/zone.js?31405934ea8c08e72de05c03ca00a77319718226:595:35)'

Finished in 0.002 secs / 0 secs @ 14:15:21 GMT-0500 (Central Daylight Time)

SUMMARY:
**√ 0 tests completed
**[14:15:22] 'karma.run.without_coverage' errored after 24 s**
[14:15:22] Error: task completion callback called too many times**
    at finish (C:\Code\Marcom-NexGen\UI\Prod\MCX_6.0.1_Version_2\node_modules\orchestrator\lib\runTask.js:15:10)
    at cb (C:\Code\Marcom-NexGen\UI\Prod\MCX_6.0.1_Version_2\node_modules\orchestrator\lib\runTask.js:29:3)
    at C:\Code\Marcom-NexGen\UI\Prod\MCX_6.0.1_Version_2\tools\tasks\seed\karma.run.without_coverage.ts:10:5
    at removeAllListeners (C:\Code\Marcom-NexGen\UI\Prod\MCX_6.0.1_Version_2\node_modules\karma\lib\server.js:333:9)
    at webServer.close (C:\Code\Marcom-NexGen\UI\Prod\MCX_6.0.1_Version_2\node_modules\karma\lib\server.js:343:11)
    at Server.close (net.js:1608:9)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at Server.emit (events.js:208:7)
    at emitCloseNT (net.js:1659:8)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
