### ISSUE TITLE
Rollup build does not work with common 3rd party libraries

### ISSUE THREAD

**Issue by nyxz** [mgechev/angular-seed#2093]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
When I try to use some common 3rd party library (like lodash) with the seed and run production build with Rollup:

```
npm run build.prod.rollup.aot
```

I get the following error:
```
[13:13:56] Finished 'build.bundles.app.rollup.aot' after 2.83 s
[13:13:56] Starting 'transpile.bundles.rollup.aot'...

/home/nyxz/dev/workspaces/js/angular-seed/node_modules/lodash/lodash.js:494
      case 0: return func.call(thisArg);
                          ^
SyntaxError: Invalid or unexpected token
    at /home/nyxz/dev/workspaces/js/angular-seed/node_modules/lodash/lodash.js:14843:16
    at apply (/home/nyxz/dev/workspaces/js/angular-seed/node_modules/lodash/lodash.js:494:27)
    at /home/nyxz/dev/workspaces/js/angular-seed/node_modules/lodash/lodash.js:15227:16
    at apply (/home/nyxz/dev/workspaces/js/angular-seed/node_modules/lodash/lodash.js:496:27)
    at /home/nyxz/dev/workspaces/js/angular-seed/node_modules/lodash/lodash.js:6600:16
    at template (/home/nyxz/dev/workspaces/js/angular-seed/node_modules/lodash/lodash.js:14842:20)
    at DestroyableTransform._transform (/home/nyxz/dev/workspaces/js/angular-seed/node_modules/gulp-template/index.js:20:14)
    at DestroyableTransform.Transform._read (/home/nyxz/dev/workspaces/js/angular-seed/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (/home/nyxz/dev/workspaces/js/angular-seed/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:170:83)
    at doWrite (/home/nyxz/dev/workspaces/js/angular-seed/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:406:64)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-seed@1.0.0 serve.prod.rollup.aot: `gulp serve.prod.rollup.aot --color --env-config prod --build-type prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-seed@1.0.0 serve.prod.rollup.aot script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nyxz/.npm/_logs/2017-09-26T10_14_01_511Z-debug.log
```

**Expected behavior**
Build without error as it builds with:

```
npm run build.prod.aot
```

**Minimal reproduction of the problem with instructions**

```
➜  ~ npm install --save lodash @types/lodash
```

In `project.config.ts`:

    let additionalPackages: ExtendPackages[] = [{
        name: 'lodash',
        path: 'node_modules/lodash/lodash.js'
      }];

    this.addPackagesBundles(additionalPackages);

In `app.component.ts`:

```
import { Component } from '@angular/core';

import * as _ from 'lodash';

@Component({
  moduleId: module.id,
  selector: 'sd-app',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.css'],
})
export class AppComponent {
  constructor() {
    console.log('Is equal? ' + (_.isEqual({age: 1}, {age: 1})));
  }
}
```

Run the following to get the error:
```
➜  ~ npm run serve.prod.rollup.aot
```

**NOTE**: 
```
➜  ~ npm start
```
runs without any error and I get the following message in the console:
> Is equal? true

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Fedora 24, VS Code, NPM 5.4.1

* **Angular Seed Version:** `eace08df83f8d632a4705e29cfa492d4060b4f54`

* **Node:** `node --version` = v6.10.2

**Comment by mgechev** [comment]
@nyxz sorry for the delay. The problem is from lodash's `template` which produces invalid JavaScript, which later tries to evaluate.

You can workaround the issue by commenting part of `transpile.bundles.rollup.aot.ts`:

```diff
export = () => {
  const tsProject = makeTsProject(
    {
      allowJs: true,
      noFallthroughCasesInSwitch: false
    },
    Config.TMP_DIR
  );
  const src = [join(Config.TMP_DIR, 'bundle.js')];
  const result = gulp
    .src(src)
    .pipe(plugins.plumber())
    .pipe(
      Config.PRESERVE_SOURCE_MAPS
        ? plugins.sourcemaps.init({ loadMaps: true, largeFile: true })
        : plugins.util.noop()
    )
    .pipe(tsProject())
    .once('error', function(e: any) {
      this.once('finish', () => process.exit(1));
    });

  return result.js
    .pipe(
      Config.PRESERVE_SOURCE_MAPS
        ? plugins.sourcemaps.write()
        : plugins.util.noop()
    )
-    .pipe(
-      plugins.template(
-        new TemplateLocalsBuilder().build(),
-        Config.TEMPLATE_CONFIG
-      )
-    )
+//    .pipe(
+//      plugins.template(
+//        new TemplateLocalsBuilder().build(),
+//        Config.TEMPLATE_CONFIG
+//      )
+//    )
    .pipe(plugins.rename(Config.JS_PROD_APP_BUNDLE))
    .pipe(gulp.dest(Config.JS_DEST))
    .on('error', (e: any) => {
      console.log(e);
    });
};
```

This will respectively disable the template replacements that we provide in JavaScript.

**Comment by nyxz** [comment]
Yes, this fixed the issue. Thank you, @mgechev !
