### ISSUE TITLE
Using D3 with angular seed

### ISSUE THREAD

**Issue by pp23** [mgechev/angular-seed#2126]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

Using for instance d3-polygon within a component causes the following error in the developer console of the browser:

```
SyntaxError: Unexpected token <
    at eval (<anonymous>)
    at evaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1510417748160:2822:16)
    at http://localhost:5555/node_modules/systemjs/dist/system.src.js?1510417748160:3622:21
    at dynamicExecute (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1510417748160:1144:26)
    at doEvaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1510417748160:1091:13)
    at doEvaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1510417748160:1051:17)
    at ensureEvaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1510417748160:999:13)
    at http://localhost:5555/node_modules/systemjs/dist/system.src.js?1510417748160:1017:20
    at Object.eval (http://localhost:5555/app/editor/editor.component.js:14:20)
    at eval (http://localhost:5555/app/editor/editor.component.js:44:4) Not expecting this error? Report it at https://github.com/mgechev/angular-seed/issues
```

**Expected behavior**

No error and D3 is usable.

**Minimal reproduction of the problem with instructions**

Install d3-polygon with `npm install @types/d3-polygon --save` and use the test code in a component:

```
import {polygonArea} from 'd3-polygon';

@Component({
	moduleId: module.id,
	selector: 'sd-editor',
	templateUrl: 'editor.component.html',
	styleUrls: ['editor.component.css']
})
export class EditorComponent implements OnInit {
	constructor() {}
	
	ngOnInit() {
		// -----------------------------------------------------------------------------
// Preparatory Steps
// -----------------------------------------------------------------------------
let num: number;
let polygon: Array<[number, number]> = [[10, 10], [20, 20], [10, 30]];

// -----------------------------------------------------------------------------
// Tests
// -----------------------------------------------------------------------------
num = polygonArea(polygon);

```
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular Seed Version:** `821d745847a378bce0a7746fb2be1b1123417370`

* **Node:** `node --version` =6.12.0

Reading some relating issues, I have already added 

`'d3-polygon':'node_modules/d3-polygon/index.js'` to SYSTEM_CONFIG_DEV. Restarting npm I get the message

```
localhost/:51 TypeError: Unable to dynamically transpile ES module
   A loader plugin needs to be configured via `SystemJS.config({ transpiler: 'transpiler-module' })`.
    at transpile (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1510418485239:3691:11)
    at http://localhost:5555/node_modules/systemjs/dist/system.src.js?1510418485239:3473:12
    at ZoneDelegate.invoke (http://localhost:5555/node_modules/zone.js/dist/zone.js?1510418485240:391:26)
    at Zone.run (http://localhost:5555/node_modules/zone.js/dist/zone.js?1510418485240:141:43)
    at http://localhost:5555/node_modules/zone.js/dist/zone.js?1510418485240:818:57
    at ZoneDelegate.invokeTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1510418485240:424:31)
    at Zone.runTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1510418485240:191:47)
    at drainMicroTaskQueue (http://localhost:5555/node_modules/zone.js/dist/zone.js?1510418485240:584:35)
    at <anonymous> Not expecting this error? Report it at https://github.com/mgechev/angular-seed/issues
```
So I have installed systemjs-babel-plugin and added the following lines to SYSTEM_CONFIG_DEV:

```
map: {
      'plugin-babel': 'node_modules/systemjs-plugin-babel/plugin-babel.js',
      'systemjs-babel-build': 'node_modules/systemjs-plugin-babel/systemjs-babel-browser.js'
    },
    transpiler: 'plugin-babel'
```

Regarding to this solution: https://stackoverflow.com/questions/45605805/angular-2-unable-to-dynamically-transpile-es-module-angular2-google-map-auto

But then I got the initial error. Could it be, that babel doesn't get called? Did I miss something? Is there another fix for this?

**Comment by mgechev** [comment]
For support requests you can use [gitter](https://gitter.im/mgechev/angular2-seed) or take a look at [project's the wiki page](https://github.com/mgechev/angular2-seed/wiki) in order to get more complete idea on how the it works.
