### ISSUE TITLE
Cannot import scss in node_modules with relative path

### ISSUE THREAD

**Issue by miloszsobczak** [mgechev/angular-seed#2169]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
I have same own npm private package - a module with components and its files: *.scss
It looks like that (`node_modules/ng-package`):
```
├── bundles
│   ├── ng-package.js
│   └── ng-package.js.map
├── index.d.ts
├── index.js
├── index.js.map
├── index.metadata.json
├── index.ngfactory.d.ts
├── index.ngfactory.js
├── index.ngfactory.js.map
├── index.ngsummary.json
├── layout
│   ├── layout-config.d.ts
│   ├── layout-config.js
│   ├── layout-config.js.map
│   ├── layout-config.metadata.json
│   ├── layout-config.ngfactory.js.map
│   ├── layout-config.ngsummary.json
│   ├── layout.d.ts
│   ├── layout.html
│   ├── layout.js
│   ├── layout.js.map
│   ├── layout.metadata.json
│   ├── layout.module.d.ts
│   ├── layout.module.js
│   ├── layout.module.js.map
│   ├── layout.module.metadata.json
│   ├── layout.module.ngfactory.d.ts
│   ├── layout.module.ngfactory.js
│   ├── layout.module.ngfactory.js.map
│   ├── layout.module.ngsummary.json
│   ├── layout.ngfactory.d.ts
│   ├── layout.ngfactory.js
│   ├── layout.ngfactory.js.map
│   └── layout.ngsummary.json
├── logo
│   ├── logo-config.d.ts
│   ├── logo-config.js
│   ├── logo-config.js.map
│   ├── logo-config.metadata.json
│   ├── logo-config.ngfactory.js.map
│   ├── logo-config.ngsummary.json
│   ├── logo.svg
│   ├── logo.d.ts
│   ├── logo.html
│   ├── logo.js
│   ├── logo.js.map
│   ├── logo.metadata.json
│   ├── logo.module.d.ts
│   ├── logo.module.js
│   ├── logo.module.js.map
│   ├── logo.module.metadata.json
│   ├── logo.module.ngfactory.d.ts
│   ├── logo.module.ngfactory.js
│   ├── logo.module.ngfactory.js.map
│   ├── logo.module.ngsummary.json
│   ├── logo.ngfactory.d.ts
│   ├── logo.ngfactory.js
│   ├── logo.ngfactory.js.map
│   └── logo.ngsummary.json
├── package.json
├── style
│   └── scss
│       └── bootstrap
│           ├── _alert.scss
│           ├── bootstrap-grid.scss
│           ├── bootstrap-reboot.scss
│           ├── bootstrap.scss
│           ├── mixins
│           │   ├── _alert.scss
│           │   ├── [and more...]
│           └── utilities
│               ├── _align.scss
│               ├── [and more...]
```

layout.js

```
import {Component} from '@angular/core';
import {NgeLayoutConfig} from './layout-config';

import '../style/scss/bootstrap/bootstrap.scss';

@Component({
  selector: 'nge-layout',
  moduleId: module.id,
  template: '<main><ng-content></ng-content></main>'
})
export class NgeLayout {

  constructor(config: NgeLayoutConfig) {

  }
}
```

During development own package it works (using sass-loader, css-laoder etc).
Here it doesn't.

When I open browser the console shows me:

```
Error: Cannot find module "../style/scss/bootstrap/bootstrap.scss"
    at webpackMissingModule (http://localhost:5555/node_modules/ng-package/bundles/ng-package.js:3321:65)
    at Object.c (http://localhost:5555/node_modules/ng-package/bundles/ng-package.js:3321:180)
    at __webpack_require__ (http://localhost:5555/node_modules/ng-package/bundles/ng-package.js:30:30)
    at Object.c (http://localhost:5555/node_modules/ng-package/bundles/ng-package.js:3283:16)
    at __webpack_require__ (http://localhost:5555/node_modules/ng-package/bundles/ng-package.js:30:30)
    at Object.module.exports (http://localhost:5555/node_modules/ng-package/bundles/ng-package.js:5088:23)
    at __webpack_require__ (http://localhost:5555/node_modules/ng-package/bundles/ng-package.js:30:30)
    at module.exports (http://localhost:5555/node_modules/ng-package/bundles/ng-package.js:73:18)
    at eval (http://localhost:5555/node_modules/ng-package/bundles/ng-package.js:76:10)
```

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
OSX, 

* **Angular Seed Version:** `1.0.0`

* **Node:** `node --version` = v6.11.1

**Comment by miloszsobczak** [comment]
Any ideas how to make it work?

**Comment by kzimny** [comment]
Did you try with styleUrls?
```
@Component({
  selector: 'nge-layout',
  moduleId: module.id,
  template: '<main><ng-content></ng-content></main>',
styleUrls: [/style/scss/bootstrap/bootstrap.scss']
})
```

**Comment by vyakymenko** [comment]
Hi @miloszsobczak , to import any styles inside component you need to configure it like:

File structure:
```sh
├── example.component.html
├── example.component.ts
└── example.component.scss
```

Component code:

```ts
...
@Component({
  moduleId: module.id,
  selector: 'sd-example,
  templateUrl: 'sd-example.component.html',
  styleUrls: ['sd-example.component.css']
})
...
```

And inside `project.config.ts` you need to enable scss `this.ENABLE_SCSS = true;`.

After all these settings you can import whatever you want inside you `*.scss` files.


@mgechev , we can close this issue I think

**Comment by miloszsobczak** [comment]
thanks.
