### ISSUE TITLE
bootstrapping TypeError: Cannot read property 'type' of null

### ISSUE THREAD

**Issue by HansKrywaa** [mgechev/angular-seed#2229]
**I'm submitting a ...**  
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

While updating my Angular Version in an existing Project to 2.0.0-rc.5 with this [Tutorial](https://www.barbarianmeetscoding.com/blog/2016/08/13/updating-your-angular-2-app-from-rc4-to-rc5-a-practical-guide/) i now get the following Error:

```
Error: TypeError: Cannot read property 'type' of null
	    at eval (http://localhost:5000/node_modules/@angular/compiler/src/metadata_resolver.js:698:42)
	    at Array.forEach (<anonymous>)
	    at getTransitiveModules (http://localhost:5000/node_modules/@angular/compiler/src/metadata_resolver.js:697:13)
	    at CompileMetadataResolver._getTransitiveNgModuleMetadata (http://localhost:5000/node_modules/@angular/compiler/src/metadata_resolver.js:411:33)
	    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:5000/node_modules/@angular/compiler/src/metadata_resolver.js:283:43)
	    at RuntimeCompiler._compileComponents (http://localhost:5000/node_modules/@angular/compiler/src/runtime_compiler.js:150:47)
	    at RuntimeCompiler._compileModuleAndComponents (http://localhost:5000/node_modules/@angular/compiler/src/runtime_compiler.js:72:37)
	    at RuntimeCompiler.compileModuleAsync (http://localhost:5000/node_modules/@angular/compiler/src/runtime_compiler.js:49:21)
	    at PlatformRef_._bootstrapModuleWithZone (http://localhost:5000/node_modules/@angular/core/src/application_ref.js:368:25)
	    at PlatformRef_.bootstrapModule (http://localhost:5000/node_modules/@angular/core/src/application_ref.js:361:21)
	Evaluating http://localhost:5000/main.js
```

**My app.module.ts:**
```
@NgModule({
  imports: [
    BrowserModule,
    routing,
    FORM_DIRECTIVES,
    CHART_DIRECTIVES,
    CORE_DIRECTIVES,
    TOOLTIP_DIRECTIVES,
    HttpModule,
    DeprecatedFormsModule
  ],       // module dependencies
  declarations: [
    AppComponent,
    MarkSearchPipe,
    DateTimePipe,
    SearchPipe,
    LimitPipe,
    TimepickerComponent,
    NavbarComponent,
    FooterComponent
  ],   // components and directives
  bootstrap: [
    AppComponent
  ],     // root component
  providers: [
    AdminService,
    AuthService,
    Roles,
    HttpClient,
    Genders,
    AdPermissions,
    HTTP_PROVIDERS,
    CookieService,
    AppConfig,
    WebsocketNotificationHandler
  ]                   // services
})
export class AppModule {
}
```
**My main.ts:**
```
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import {AppModule} from './app/app.module';

platformBrowserDynamic().bootstrapModule(AppModule).catch(err => console.error(err));
```

Is my app.module.ts wrong? 
I tried a lot, nothing worked...

**Comment by mgechev** [comment]
Angular 2 RC 5 is no longer supported by us, although you can find a working tag.
