### ISSUE TITLE
Occurred Error when I start up this project

### ISSUE THREAD

**Issue by kunkuntang** [mgechev/angular-seed#2263]
I'm submitting a problem after I cloned your project and occurred a error while I installing the dependences by using NPM, the error occurred when gulp starting the task which 'check.versions' and show error type is told:  

**Current behavior**

```
TSError: ⨯ Unable to compile TypeScript, tools/tasks/seed/check.versions.ts (18,36): Cannot find name 'NodeBuffer'. (2304) 
tools/tasks/seed/check.versions.ts (18,56): Cannot find name 'NodeBuffer'. (2304)
tools/tasks/seed/check.versions.ts (29,36): Cannot find name 'NodeBuffer'. (2304)
tools/tasks/seed/check.versions.ts (29,56): Cannot find name 'NodeBuffer'. (2304)
    at getOutput (/Users/kuntang/Documents/learning/angular-seed/node_modules/_ts-node@6.0.2@ts-node/src/index.ts:330:15)
    at Object.compile (/Users/kuntang/Documents/learning/angular-seed/node_modules/_ts-node@6.0.2@ts-node/src/index.ts:516:11)
    at Module.m._compile (/Users/kuntang/Documents/learning/angular-seed/node_modules/_ts-node@6.0.2@ts-node/src/index.ts:403:43)
    at Module._extensions..js (module.js:671:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/kuntang/Documents/learning/angular-seed/node_modules/_ts-node@6.0.2@ts-node/src/index.ts:406:12)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
✖ Install fail! Error: post install error, please remove node_modules before retry!
Run "sh -c gulp check.versions && gulp print.banner" error, exit code 1
Error: post install error, please remove node_modules before retry!
Run "sh -c gulp check.versions && gulp print.banner" error, exit code 1
    at ChildProcess.proc.on.code (/usr/local/lib/node_modules/cnpm/node_modules/runscript/index.js:65:21)
    at ChildProcess.emit (events.js:159:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
npminstall version: 3.0.1
npminstall args: /usr/local/Cellar/node/9.3.0_1/bin/node /usr/local/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --china --userconfig=/Users/kuntang/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=http://registry.npm.taobao.org
```
**Expected behavior**

Normally start up the project.
**Minimal reproduction of the problem with instructions**

I am't not able to fixed it...

**What is the motivation / use case for changing the behavior?**

Normally start up the project.

**Please tell us about your environment:**

Mac os 10.12.6

* **Angular Seed Version:** `b766673 `

* **Node:** `node --version` = v10.0.0

**Comment by flakronkadriu** [comment]
clone the project and try yarn install instead of npm install but first install yarn,

**Comment by Johns-Chris** [comment]
I noticed this issue as well.
```
Mac OSx 10.13.4 (17E202)
Node --version: v8.11.1
npm --version: 5.6.0
```

Did a little digging, and it looks as though it's caused by commit [b766673836684296689b223a8df78e8f9e5c55b4](https://github.com/mgechev/angular-seed/commit/b766673836684296689b223a8df78e8f9e5c55b4)

reverting "ts-node" in **package.json** back to "^5.0.0", then re-running ```npm install``` seems to resolve it for me.

**Comment by vyakymenko** [comment]
This issue is resolved after migration to Angular 6.
 @mgechev , we can close the ticket.
